### ISSUE TITLE
macOS 16.4.1 NoSuchMethodError: org.opengis.referencing.crs.CoordinateReferenceSystem.getName()Lorg/opengis/metadata/Identifier; 

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#104]
```
ERROR [main] CaveLogger: Paint error: org.opengis.referencing.crs.CoordinateReferenceSystem.getName()Lorg/opengis/metadata/Identifier;:: The resource [State/County Boundaries] has been disabled.
com.raytheon.uf.viz.core.exception.VizException: Paint error: org.opengis.referencing.crs.CoordinateReferenceSystem.getName()Lorg/opengis/metadata/Identifier;:: The resource [State/County Boundaries] has been disabled.
	at com.raytheon.uf.viz.core.drawables.AbstractRenderableDisplay.paintResource(AbstractRenderableDisplay.java:628)
	at com.raytheon.uf.viz.core.maps.display.MapRenderableDisplay.paint(MapRenderableDisplay.java:188)
	at com.raytheon.uf.viz.d2d.core.map.D2DMapRenderableDisplay.paint(D2DMapRenderableDisplay.java:220)
	at com.raytheon.viz.ui.panes.VizDisplayPane.glDrawInternal(VizDisplayPane.java:523)
	at com.raytheon.viz.ui.panes.VizDisplayPane.draw(VizDisplayPane.java:477)
	at com.raytheon.viz.ui.panes.DrawCoordinatedPane.draw(DrawCoordinatedPane.java:172)
	at com.raytheon.viz.ui.panes.DrawCoordinatorJob$1.run(DrawCoordinatorJob.java:196)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:187)
	at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:97)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.NoSuchMethodError: org.opengis.referencing.crs.CoordinateReferenceSystem.getName()Lorg/opengis/metadata/Identifier;
	at com.raytheon.uf.viz.core.map.MapDescriptor.pixelToWorld(MapDescriptor.java:284)
	at com.raytheon.uf.viz.core.map.MapDescriptor.pixelToWorld(MapDescriptor.java:349)
	at com.raytheon.uf.viz.core.maps.rsc.AbstractDbMapResource.buildBoundingGeometry(AbstractDbMapResource.java:213)
	at com.raytheon.uf.viz.core.maps.rsc.DbMapResource.paintInternal(DbMapResource.java:574)
	at com.raytheon.uf.viz.core.rsc.AbstractVizResource.paint(AbstractVizResource.java:510)
	at com.raytheon.uf.viz.core.maps.rsc.MapResourceGroup.paintInternal(MapResourceGroup.java:181)
	at com.raytheon.uf.viz.core.rsc.AbstractVizResource.paint(AbstractVizResource.java:510)
	at com.raytheon.uf.viz.core.drawables.AbstractRenderableDisplay.paintResource(AbstractRenderableDisplay.java:625)
	... 35 common frames omitted
```

**Comment by mjames-upc** [comment]
```
!ENTRY org.eclipse.m2e.logback.appender 4 0 2017-02-28 18:01:29.200
!MESSAGE failed to load maven project for org.eclipse.jdt.internal.ui.javaeditor.JarEntryEditorInput@3b551f27
!STACK 1
org.eclipse.core.runtime.CoreException: Can't read Maven project
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.readMavenProject(SelectionUtil.java:330)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.getMavenProject(SelectionUtil.java:277)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.readMavenProject(MavenPomEditor.java:729)
	at org.eclipse.m2e.editor.pom.MavenPomEditor$5.run(MavenPomEditor.java:1050)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Contains: 1 problem was encountered while building the effective model for org.geotools:gt-opengis:[unknown-version]
[FATAL] Non-resolvable parent POM for org.geotools:gt-opengis:[unknown-version]: Failure to find org.geotools:library:pom:15.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 11
 for project org.geotools:gt-opengis:[unknown-version] at /var/folders/qz/ml62dq1n28d33gtkt0xj0c9w0000gn/T/maven-pom3747464787357443558.pom
org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model for org.geotools:gt-opengis:[unknown-version]
[FATAL] Non-resolvable parent POM for org.geotools:gt-opengis:[unknown-version]: Failure to find org.geotools:library:pom:15.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 11
 for project org.geotools:gt-opengis:[unknown-version] at /var/folders/qz/ml62dq1n28d33gtkt0xj0c9w0000gn/T/maven-pom3747464787357443558.pom
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:168)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil$1.call(SelectionUtil.java:314)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil$1.call(SelectionUtil.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.readMavenProject(SelectionUtil.java:312)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.getMavenProject(SelectionUtil.java:277)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.readMavenProject(MavenPomEditor.java:729)
	at org.eclipse.m2e.editor.pom.MavenPomEditor$5.run(MavenPomEditor.java:1050)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.geotools:gt-opengis:[unknown-version]
[FATAL] Non-resolvable parent POM for org.geotools:gt-opengis:[unknown-version]: Failure to find org.geotools:library:pom:15.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 11

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1007)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:796)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:325)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:161)
	... 12 more
!SUBENTRY 1 org.eclipse.m2e.core 4 4 2017-02-28 18:01:29.201
!MESSAGE Can't read Maven project
!SUBENTRY 2 org.eclipse.m2e.core 4 -1 2017-02-28 18:01:29.201
!MESSAGE 1 problem was encountered while building the effective model for org.geotools:gt-opengis:[unknown-version]
[FATAL] Non-resolvable parent POM for org.geotools:gt-opengis:[unknown-version]: Failure to find org.geotools:library:pom:15.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 11
 for project org.geotools:gt-opengis:[unknown-version] at /var/folders/qz/ml62dq1n28d33gtkt0xj0c9w0000gn/T/maven-pom3747464787357443558.pom
!STACK 0
org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model for org.geotools:gt-opengis:[unknown-version]
[FATAL] Non-resolvable parent POM for org.geotools:gt-opengis:[unknown-version]: Failure to find org.geotools:library:pom:15.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 11
 for project org.geotools:gt-opengis:[unknown-version] at /var/folders/qz/ml62dq1n28d33gtkt0xj0c9w0000gn/T/maven-pom3747464787357443558.pom
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:168)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil$1.call(SelectionUtil.java:314)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil$1.call(SelectionUtil.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.readMavenProject(SelectionUtil.java:312)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.getMavenProject(SelectionUtil.java:277)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.readMavenProject(MavenPomEditor.java:729)
	at org.eclipse.m2e.editor.pom.MavenPomEditor$5.run(MavenPomEditor.java:1050)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for org.geotools:gt-opengis:[unknown-version]
[FATAL] Non-resolvable parent POM for org.geotools:gt-opengis:[unknown-version]: Failure to find org.geotools:library:pom:15.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 11

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:197)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1007)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:796)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:325)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:161)
	... 12 more


```

**Comment by mjames-upc** [comment]
Solution is to remove jscience.jar from /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/ to avoid exposing duplicate org.opengis.metadata classes.
