### ISSUE TITLE
libbignsharp.dylib Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#105]
```
WARN  [Worker-2] CaveLogger: An Error occured loading nsharp libraries, nsharp will not work.
java.lang.UnsatisfiedLinkError: awips2-ncep/viz/gov.noaa.nws.ncep.ui.nsharp.macosx/libbignsharp.dylib: dlopen(awips2-ncep/viz/gov.noaa.nws.ncep.ui.nsharp.macosx/libbignsharp.dylib, 1): Library not loaded: /usr/local/lib/gcc/4.9/libgfortran.3.dylib
  Referenced from: awips2-ncep/viz/gov.noaa.nws.ncep.ui.nsharp.macosx/libbignsharp.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at gov.noaa.nws.ncep.ui.nsharp.Activator.start(Activator.java:74)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.raytheon.uf.viz.core.reflect.SubClassLocator.loadClassesFromCache(SubClassLocator.java:283)
	at com.raytheon.uf.viz.core.reflect.SubClassLocator.lookupRecursiveSubClasses(SubClassLocator.java:189)
	at com.raytheon.uf.viz.core.reflect.SubClassLocator.getRequiredSubclasses(SubClassLocator.java:222)
	at com.raytheon.uf.viz.core.reflect.SubClassLocator.lookupRecursiveSubClasses(SubClassLocator.java:192)
	at com.raytheon.uf.viz.core.reflect.SubClassLocator.locateSubClasses(SubClassLocator.java:107)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processClass(JAXBClassLocator.java:103)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processClass(JAXBClassLocator.java:88)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processField(JAXBClassLocator.java:125)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processClass(JAXBClassLocator.java:112)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processClass(JAXBClassLocator.java:88)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processField(JAXBClassLocator.java:125)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.processClass(JAXBClassLocator.java:112)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.<init>(JAXBClassLocator.java:76)
	at com.raytheon.uf.common.serialization.jaxb.JAXBClassLocator.getJAXBClasses(JAXBClassLocator.java:197)
	at com.raytheon.uf.viz.core.procedures.ProcedureXmlManager.initManager(ProcedureXmlManager.java:110)
	at com.raytheon.uf.viz.core.procedures.ProcedureXmlManager.<init>(ProcedureXmlManager.java:105)
	at com.raytheon.uf.viz.core.procedures.ProcedureXmlManager.getInstance(ProcedureXmlManager.java:81)
	at com.raytheon.uf.viz.core.procedures.ProcedureXmlManager$1.run(ProcedureXmlManager.java:96)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mjames-upc** [comment]
No longer relevant after NSHARP was rewritten in Java.
