### ISSUE TITLE
MapManager: EDEX - Error in retrieving last update time for map named [TropicalISC]: Could not find table [nhadomain] in maps database.

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#109]
```
ERROR 2017-03-21 01:32:31,494 9758 [pool-2-thread-1] MapManager: EDEX - Error in retrieving last update time for map named [TropicalISC]: Could not find table [nhadomain] in maps database.
com.raytheon.edex.plugin.gfe.exception.MissingLocalMapsException: com.raytheon.edex.plugin.gfe.exception.GfeConfigurationException: Missing database table for map nhadomain
        at com.raytheon.edex.plugin.gfe.reference.DbShapeSource.getLastUpdated(DbShapeSource.java:463) ~[com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.reference.MapManager.updateNeeded(MapManager.java:290) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.reference.MapManager.<init>(MapManager.java:230) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.reference.MapManager.<init>(MapManager.java:170) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.server.IFPServer.<init>(IFPServer.java:221) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.server.IFPServer.activateServer(IFPServer.java:149) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.config.GFESiteActivation.internalActivateSite(GFESiteActivation.java:305) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.config.GFESiteActivation.activateSite(GFESiteActivation.java:243) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.uf.edex.site.SiteAwareRegistry$1.run(SiteAwareRegistry.java:134) [com.raytheon.uf.edex.site.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
Caused by: com.raytheon.edex.plugin.gfe.exception.GfeConfigurationException: Missing database table for map nhadomain
        at com.raytheon.edex.plugin.gfe.reference.DbShapeSource.getLastUpdated(DbShapeSource.java:458) ~[com.raytheon.edex.plugin.gfe.jar:na]
        ... 13 common frames omitted

```

**Comment by mjames-upc** [comment]
possibly related

```
ERROR 2017-03-21 01:32:31,500 9760 [EDEXMain] SetupSrv: EDEX - OHD Setup did not successfully complete: Error while copying localization files: /awips2/edex/data/share/hydroapps/precip_proc/local/data/app/mpe/prism/prism_max_temp_oax_jun
```
