### ISSUE TITLE
[Ingest.ncuair-1] PersistSrv: Persisting record /TTCC_HGHT failed.

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#110]
```
ERROR 2017-03-21 01:32:44,062 1917 [Ingest.ncuair-1] PersistSrv: Persisting record /TTCC_HGHT failed.
com.raytheon.uf.common.datastorage.StorageException: Error processing StoreRequest on file /awips2/edex/data/hdf5/ncuair/ncuairs-2017-03-21-00.h5: Traceback (most recent call last):
   File "/awips2/python/lib/python2.7/site-packages/pypies/handlers.py", line 96, in pypies_response
    resp = datastoreMap[clz][0](obj)
   File "/awips2/python/lib/python2.7/site-packages/pypies/impl/H5pyDataStore.py", line 143, in store
    LockManager.releaseLock(lock)
   File "/awips2/python/lib/python2.7/site-packages/pypies/MkDirLockManager.py", line 201, in releaseLock
    os.rmdir(lockPath)
 OSError: [Errno 2] No such file or directory: '/awips2/edex/data/hdf5/ncuair/ncuairs-2017-03-21-00.h5_write'

        at com.raytheon.uf.common.pypies.PyPiesDataStore.store(PyPiesDataStore.java:270) ~[com.raytheon.uf.common.pypies.jar:na]
        at com.raytheon.uf.edex.pointdata.PointDataPluginDao.persistToHDF5(PointDataPluginDao.java:202) ~[com.raytheon.uf.edex.pointdata.jar:na]
        at com.raytheon.uf.edex.ingest.PersistSrv.persist(PersistSrv.java:91) ~[com.raytheon.uf.edex.ingest.jar:na]
        at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[na:na]

```

**Comment by jibeizhao** [comment]
We run into the same issue, i believe the h5_write was deleted before it should be.
We tried to set the thread number to 1, this is still happening.
