### ISSUE TITLE
WarningDecoder.py line 445: Did not find either the product DTG or the pil:  WTPQ20

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#111]
```
====210132 ARP UAL52 4935N04507W 0131 F320 4959N04000W 0152 5059N03000W MS50

 274/126 KT

N66057 DDL XXW 210132 F85A
ERROR 2017-03-21 01:33:17,041 4155 [Ingest.Warning-1] EdexLogStream: /awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py line 445: Did not find either the product DTG or the pil:  WTPQ20 BABJ 210000
NIL
^C None

===============>toPointData

```

**Comment by mjames-upc** [comment]
```
ERROR 2017-03-21 01:33:17,047 4157 [Ingest.Warning-1] warning: Exchange[ExchangePattern: InOnly, BodyType: java.io.File, Body: [Body is file based: /awips2/data_store/wwa/WTPQ20_BABJ_210000_35142775.2017032101], CaughtExceptionType: com.raytheon.edex.exception.DecoderException, CaughtExceptionMessage: jep.JepException: <type 'exceptions.Exception'>: Product DTG or Pil missing, StackTrace: com.raytheon.edex.exception.DecoderException: jep.JepException: <type 'exceptions.Exception'>: Product DTG or Pil missing
        at com.raytheon.uf.edex.python.decoder.PythonDecoder.decode(PythonDecoder.java:107)
        at com.raytheon.uf.edex.python.decoder.PythonDecoder.decode(PythonDecoder.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

```

**Comment by mjames-upc** [comment]
distribution file regex match for convective outlook reports is incorrect?

```
grep "Body is file based" *| grep Warning | cut -c 174-250|cut -d"," -f1 | sed 's/\]//' | cut -d "_" -f 1,2,3 | sort | uniq
/awips2/data_store/forecast/FZAA02_SCSC
/awips2/data_store/forecast/FZAK41_KWNO
/awips2/data_store/forecast/FZAK61_PAJK
/awips2/data_store/forecast/FZAK63_PAFC
/awips2/data_store/forecast/FZAK64_PAFC
/awips2/data_store/forecast/FZCA52_TJSJ
/awips2/data_store/forecast/FZHW51_PHFO
/awips2/data_store/forecast/FZHW61_PHFO
/awips2/data_store/forecast/FZPS04_SCSC
/awips2/data_store/forecast/FZPS40_PHFO
/awips2/data_store/forecast/FZUS81_KWBC
/awips2/data_store/wwa/WOPS01_NFFN
/awips2/data_store/wwa/WTPQ20_BABJ
/awips2/data_store/wwa/WUUS01_KWNS
/awips2/data_store/wwa/WUUS02_KWNS
/awips2/data_store/wwa/WUUS03_KWNS
/awips2/data_store/wwa/WWAA02_SAWB
/awips2/data_store/wwa/WWPK19_OPKC
/awips2/data_store/wwa/WWPK20_OPKC
/awips2/data_store/wwa/WWPK31_OPMT
/awips2/data_store/wwa/WWUS30_KWNS
/awips2/data_store/wwa/WWUS60_KWNS
```

ERROR 2017-03-31 07:01:42,711 7399 [Ingest.Warning-1] warning: Exchange[ExchangePattern: InOnly, BodyType: java.io.File, Body: [Body is file based: /awips2/data_store/wwa/WUUS02_KWNS_310524_5533574.2017033105], CaughtExceptionType: com.raytheon.edex.exception.DecoderException, CaughtExceptionMessage: jep.JepException: <type 'exceptions.Exception'>: No UGC line to end overview text, StackTrace: com.raytheon.edex.exception.DecoderException: jep.JepException: <type 'exceptions.Exception'>: No UGC line to end overview text

**Comment by mjames-upc** [comment]
FZUS "NEARSHORE MARINE FORECAST"

**Comment by mjames-upc** [comment]
find /awips2/data_store/ -name "FZ*" | cut -d "_" -f 1,2,3 | sort | uniq
/awips2/data_store/forecast/FZHW60_PHFO
/awips2/data_store/forecast/FZHW61_PHFO
/awips2/data_store/forecast/FZNT02_KNHC
/awips2/data_store/forecast/FZPN01_KWBC
/awips2/data_store/forecast/FZPN04_KNHC
/awips2/data_store/forecast/FZPN25_KWBC
/awips2/data_store/forecast/FZPN26_KWBC
/awips2/data_store/forecast/FZPN36_KWBC
/awips2/data_store/forecast/FZPN40_PHFO
/awips2/data_store/forecast/FZPS40_PHFO
/awips2/data_store/forecast/FZUS51_KBOX
/awips2/data_store/forecast/FZUS51_KCAR
/awips2/data_store/forecast/FZUS51_KLWX
/awips2/data_store/forecast/FZUS51_KOKX
/awips2/data_store/forecast/FZUS52_KJAX
/awips2/data_store/forecast/FZUS53_KGRB
/awips2/data_store/forecast/FZUS53_KMQT
/awips2/data_store/forecast/FZUS54_KBRO
/awips2/data_store/forecast/FZUS54_KCRP
/awips2/data_store/forecast/FZUS54_KMOB
/awips2/data_store/forecast/FZUS56_KEKA
/awips2/data_store/forecast/FZUS56_KLOX
/awips2/data_store/forecast/FZUS56_KMFR
/awips2/data_store/forecast/FZUS56_KMTR
/awips2/data_store/forecast/FZUS56_KPQR
/awips2/data_store/forecast/FZUS71_KLWX
/awips2/data_store/forecast/FZUS72_KMHX

**Comment by mjames-upc** [comment]
/awips2/data_store/forecast/FZAA02_SCSC
 /awips2/data_store/forecast/FZAK51_PAFC
 /awips2/data_store/forecast/FZAK51_PAFG
 /awips2/data_store/forecast/FZAK51_PAJK
 /awips2/data_store/forecast/FZAK52_PAFC
 /awips2/data_store/forecast/FZAK52_PAFG
 /awips2/data_store/forecast/FZAK52_PAJK
 /awips2/data_store/forecast/FZAK53_PAJK
 /awips2/data_store/forecast/FZAK61_PAFC
 /awips2/data_store/forecast/FZAK61_PAFG
 /awips2/data_store/forecast/FZAK62_PAFC
 /awips2/data_store/forecast/FZAK62_PAFG
 /awips2/data_store/forecast/FZAK64_PAFC
 /awips2/data_store/forecast/FZAK67_PAJK
 /awips2/data_store/forecast/FZAK69_PAFG
 /awips2/data_store/forecast/FZCA52_TJSJ
 /awips2/data_store/forecast/FZHW50_PHFO
 /awips2/data_store/forecast/FZHW50_PHFO)
 /awips2/data_store/forecast/FZHW52_PHFO
 /awips2/data_store/forecast/FZHW60_PHFO
 /awips2/data_store/forecast/FZMY50_PGUM
 /awips2/data_store/forecast/FZPQ51_PGUM
 /awips2/data_store/forecast/FZPQ52_PGUM
 /awips2/data_store/forecast/FZPS04_SCSC
 /awips2/data_store/forecast/FZPS40_PHFO
 /awips2/data_store/forecast/FZUS51_KAKQ
 /awips2/data_store/forecast/FZUS51_KBOX
 /awips2/data_store/forecast/FZUS51_KBUF
 /awips2/data_store/forecast/FZUS51_KCAR
 /awips2/data_store/forecast/FZUS51_KCLE
 /awips2/data_store/forecast/FZUS51_KGYX
 /awips2/data_store/forecast/FZUS51_KLWX
 /awips2/data_store/forecast/FZUS51_KOKX
 /awips2/data_store/forecast/FZUS51_KPHI
 /awips2/data_store/forecast/FZUS52_KCHS
 /awips2/data_store/forecast/FZUS52_KILM
 /awips2/data_store/forecast/FZUS52_KILM)
 /awips2/data_store/forecast/FZUS52_KJAX
 /awips2/data_store/forecast/FZUS52_KKEY
 /awips2/data_store/forecast/FZUS52_KMFL
 /awips2/data_store/forecast/FZUS52_KMHX
 /awips2/data_store/forecast/FZUS52_KMLB
 /awips2/data_store/forecast/FZUS52_KTAE
 /awips2/data_store/forecast/FZUS52_KTBW
 /awips2/data_store/forecast/FZUS53_KAPX
 /awips2/data_store/forecast/FZUS53_KDLH
 /awips2/data_store/forecast/FZUS53_KDTX
 /awips2/data_store/forecast/FZUS53_KGRB
 /awips2/data_store/forecast/FZUS53_KGRR
 /awips2/data_store/forecast/FZUS53_KIWX
 /awips2/data_store/forecast/FZUS53_KLOT
 /awips2/data_store/forecast/FZUS53_KMKX
 /awips2/data_store/forecast/FZUS53_KMQT
 /awips2/data_store/forecast/FZUS54_KBRO
 /awips2/data_store/forecast/FZUS54_KCRP
 /awips2/data_store/forecast/FZUS54_KHGX
 /awips2/data_store/forecast/FZUS54_KLCH
 /awips2/data_store/forecast/FZUS54_KLIX
 /awips2/data_store/forecast/FZUS54_KMOB
 /awips2/data_store/forecast/FZUS56_KEKA
 /awips2/data_store/forecast/FZUS56_KLOX
 /awips2/data_store/forecast/FZUS56_KMFR
 /awips2/data_store/forecast/FZUS56_KMTR
 /awips2/data_store/forecast/FZUS56_KPQR
 /awips2/data_store/forecast/FZUS56_KSEW
 /awips2/data_store/forecast/FZUS56_KSGX
 /awips2/data_store/forecast/FZUS61_KBUF
 /awips2/data_store/forecast/FZUS61_KCLE
 /awips2/data_store/forecast/FZUS63_KDTX
 /awips2/data_store/forecast/FZUS63_KLOT
 /awips2/data_store/forecast/FZUS63_KMQT
 /awips2/data_store/forecast/FZUS71_KLWX
 /awips2/data_store/forecast/FZUS72_KCHS
 /awips2/data_store/forecast/FZUS72_KILM
 /awips2/data_store/forecast/FZUS72_KMFL
 /awips2/data_store/forecast/FZUS72_KTBW
 /awips2/data_store/forecast/FZUS73_KDTX
 /awips2/data_store/forecast/FZUS74_KMOB
