### ISSUE TITLE
Cannot run program "/awips2/edex/data/share/hydroapps/whfs/bin/run_pdc_pp": error=2, No such file or directory

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#13]
INFO  2015-09-06 16:02:00,006 [DefaultQuartzScheduler_Worker-10] JmsPooledConnection: EDEX - Creating connection: com.raytheon.uf.common.jms.JmsPooledConnection@3b510579
INFO  2015-09-06 16:02:00,010 [DefaultQuartzScheduler_Worker-5] JmsPooledProducer: EDEX - Creating AMQ producer pointDataScheduledWork
INFO  2015-09-06 16:02:00,015 [IoReceiver - edex.unidata.ucar.edu/128.117.140.100:5672] ClientDelegate: Heartbeat interval is 0 sec. Heartbeats are disabled.
INFO  2015-09-06 16:02:00,016 [DefaultQuartzScheduler_Worker-10] AMQConnection: Connection 133 now connected from /128.117.140.100:35883 to edex.unidata.ucar.edu/128.117.140.100:5672
INFO  2015-09-06 16:02:00,018 [DefaultQuartzScheduler_Worker-10] JmsPooledProducer: EDEX - Creating AMQ producer scheduledQCScanWork
WARN  2015-09-06 16:02:00,022 [pointDataScheduledWork-1] AppsDefaults: App Execution Token for App Context WhfsSrv is true
ERROR 2015-09-06 16:02:00,027 [pointDataScheduledWork-1] MainMethod: EDEX - Cannot run program "/awips2/edex/data/share/hydroapps/whfs/bin/run_pdc_pp": error=2, No such file or directory
java.io.IOException: Cannot run program "/awips2/edex/data/share/hydroapps/whfs/bin/run_pdc_pp": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_65]
        at com.raytheon.uf.edex.ohd.MainMethod.start(MainMethod.java:183) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.MainMethod.execute(MainMethod.java:142) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.ScriptService.execute(ScriptService.java:87) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.whfs.WhfsSrv.execute(WhfsSrv.java:67) [com.raytheon.uf.edex.ohd.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:407) [camel-core-2.13.2.jar:2.13.2]
        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:278) [camel-core-2.13.2.jar:2.13.2]
        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:251) [camel-core-2.13.2.jar:2.13.2]

**Comment by mjames-upc** [comment]
ERROR 2015-09-06 15:59:55,625 [EDEXMain] MainMethod: EDEX - Cannot run program "/awips2/edex/data/share/hydroapps/geo_data/util/run_create_bas_bound": error=2, No such file or directory
java.io.IOException: Cannot run program "/awips2/edex/data/share/hydroapps/geo_data/util/run_create_bas_bound": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_65]
        at com.raytheon.uf.edex.ohd.MainMethod.start(MainMethod.java:183) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.MainMethod.execute(MainMethod.java:142) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.MainMethod.runProgram(MainMethod.java:103) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.SetupSrv.executeScripts(SetupSrv.java:162) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.SetupSrv.executeSetupProcedures(SetupSrv.java:145) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.SetupSrv.execute(SetupSrv.java:81) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.SetupSrv.<init>(SetupSrv.java:64) [com.raytheon.uf.edex.ohd.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [na:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [na:1.7.0_65]
