### ISSUE TITLE
Ingest.atcf StackTrace: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#132]
```
ERROR 2017-03-30 22:06:08,710 3493 [Ingest.atcf-1] atcf: Exchange[ExchangePattern: InOnly, BodyType: null, CaughtExceptionType: java.lang.NullPointerException, CaughtExceptionMessage: null, StackTrace: java.lang.NullPointerException
        at java.lang.String.<init>(String.java:566)
        at gov.noaa.nws.ncep.edex.plugin.atcf.decoder.AtcfSeparator.setData(AtcfSeparator.java:96)
        at gov.noaa.nws.ncep.edex.plugin.atcf.decoder.AtcfSeparator.separate(AtcfSeparator.java:71)
        at gov.noaa.nws.ncep.edex.plugin.atcf.decoder.AtcfDecoder.decode(AtcfDecoder.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by mjames-upc** [comment]
believe it's incorrectly matching supplemental reports (^SH)

find /awips2/data_store/ -name "SH*"
/awips2/data_store/misc_sfc_obs/SHUS44_KLCH_311522_7010675.2017033115
/awips2/data_store/misc_sfc_obs/SHUS44_KSHV_311552_7075980.2017033115
/awips2/data_store/misc_sfc_obs/SHUS44_KJAN_311556_7087599.2017033115
/awips2/data_store/misc_sfc_obs/SHUS43_KDDC_311507_6966616.2017033115
/awips2/data_store/misc_sfc_obs/SHUS44_KOUN_311518_7007524.2017033115

cat ./utility/common_static/base/distribution/atcf.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<requestPatterns xmlns:ns2="group">
    <regex>^(WP|IO|SH|CP|EP|AL|SL).*</regex>
</requestPatterns>
```
