### ISSUE TITLE
Error processing hibernate objects for plugin com.raytheon.uf.common.dataplugin.grid

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#16]
INFO  2015-09-06 15:57:47,372 [EDEXMain] SchemaManager: Exporting DDL for com.raytheon.uf.common.dataplugin.grid plugin...
ERROR 2015-09-06 15:57:47,455 [EDEXMain] SchemaManager: Error processing hibernate objects for plugin com.raytheon.uf.common.dataplugin.grid
com.raytheon.uf.common.dataplugin.PluginException: Error occurred exporting schema, sql [create table GridCoverage (DTYPE varchar(31) not null, id int4 not null, crs varchar(2047), dx float8, dy float8, firstGridPointCorner varchar(255), the_geom GEOMETRY, la1 float8, lo1 float8, name varchar(255), nx int4, ny int4, spacingUnit varchar(255), latin1 float8, latin2 float8, lov float8, majorAxis float8, minorAxis float8, la2 float8, latin float8, lo2 float8, lad float8, primary key (id))]
        at com.raytheon.uf.edex.database.schema.SchemaManager.exportSchema(SchemaManager.java:491) ~[com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.schema.SchemaManager.pluginAdded(SchemaManager.java:280) ~[com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.DatabasePluginRegistry.register(DatabasePluginRegistry.java:90) [com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.DatabasePluginRegistry.pluginAdded(DatabasePluginRegistry.java:119) [com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.core.dataplugin.PluginRegistry.register(PluginRegistry.java:76) [com.raytheon.uf.edex.core.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]

**Comment by mjames-upc** [comment]
at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
        at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:53) [wrapperApp.jar:na]
        at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:36) [wrapperApp.jar:na]
Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:204) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1238) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at org.hibernate.internal.SQLQueryImpl.executeUpdate(SQLQueryImpl.java:401) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        at com.raytheon.uf.edex.database.dao.CoreDao$18.doInTransaction(CoreDao.java:824) ~[com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.dao.CoreDao$18.doInTransaction(CoreDao.java:1) ~[com.raytheon.uf.edex.database.jar:na]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:131) ~[spring-tx-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at com.raytheon.uf.edex.database.dao.CoreDao.executeSQLUpdate(CoreDao.java:820) ~[com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.schema.SchemaManager.exportSchema(SchemaManager.java:488) ~[com.raytheon.uf.edex.database.jar:na]
        ... 53 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "gridcoverage" already exists
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147) ~[c3p0-0.9.2.1.jar:0.9.2.1]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
        ... 61 common frames omitted
ERROR 2015-09-06 15:57:47,468 [EDEXMain] DatabasePluginRegistry: Failed to register dataplugin [grid]
com.raytheon.uf.common.util.registry.RegistryException: Plugin com.raytheon.uf.common.dataplugin.grid failed during registration
        at com.raytheon.uf.edex.database.DatabasePluginRegistry.register(DatabasePluginRegistry.java:93) ~[com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.DatabasePluginRegistry.pluginAdded(DatabasePluginRegistry.java:119) ~[com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.core.dataplugin.PluginRegistry.register(PluginRegistry.java:76) [com.raytheon.uf.edex.core.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]

**Comment by mjames-upc** [comment]
Only appears to happen on initial startup after install.  Can ignore for now.
