### ISSUE TITLE
Native library (darwin/libgempak.dylib) not found in resource path 

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#173]
ERROR 2017-06-28 08:23:32,957 9192 [Worker-1] CaveLogger: An internal error occurred during: "Ncgrid Loading...".
java.lang.UnsatisfiedLinkError: Unable to load library 'gempak': Native library (darwin/libgempak.dylib) not found in resource path (/Users/mj/.p2/pool/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at gov.noaa.nws.ncep.viz.gempak.grid.jna.GridDiag$gempak.<clinit>(GridDiag.java:98)
	at gov.noaa.nws.ncep.viz.gempak.grid.jna.GridDiag.<init>(GridDiag.java:64)
	at gov.noaa.nws.ncep.viz.gempak.grid.jna.GridDiag.getInstance(GridDiag.java:52)
	at gov.noaa.nws.ncep.viz.rsc.ncgrid.dgdriv.Dgdriv.<init>(Dgdriv.java:197)

**Comment by mjames-upc** [comment]
I've given up on building libgempak on macOS
