### ISSUE TITLE
MainMethod: EDEX - Cannot run program "ksh": error=2, No such file or directory

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#18]
ERROR 2015-09-06 20:30:34,892 [dhrProcess-1] MainMethod: EDEX - Cannot run program "ksh": error=2, No such file or directory
java.io.IOException: Cannot run program "ksh": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047) ~[na:1.7.0_65]
        at com.raytheon.uf.edex.ohd.MainMethod.start(MainMethod.java:183) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.MainMethod.execute(MainMethod.java:142) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.MainMethod.runProgram(MainMethod.java:103) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.pproc.HPEDhrSrv.runGatherScripts(HPEDhrSrv.java:248) [com.raytheon.uf.edex.ohd.jar:na]
        at com.raytheon.uf.edex.ohd.pproc.HPEDhrSrv.process(HPEDhrSrv.java:120) [com.raytheon.uf.edex.ohd.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]

**Comment by mjames-upc** [comment]
awips2-edex-dat should require ksh

**Comment by mjames-upc** [comment]
ERROR 2015-09-06 20:38:56,590 [dhrProcess-1] MainMethod: EDEX - ksh /awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather failed with exit code 1
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
runso: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
sort: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
/awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather[132]: /dhrgather_log: cannot create [Permission denied]
/awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather[134]: /dhrgather_log: cannot create [Permission denied]
touch: cannot touch `/dhrgather_control.temp': Permission denied
psql: FATAL:  no PostgreSQL user name specified in startup packet
/awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather[172]: /dhrgather_log: cannot create [Permission denied]
/awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather[179]: /radid.temp: cannot create [Permission denied]
/awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather[191]: /dhrgather_log: cannot create [Permission denied]
/awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather[194]: /dhrgather_log: cannot create [Permission denied]

ERROR 2015-09-06 20:33:25,325 [dhrProcess-1] MainMethod: EDEX - ksh /awips2/edex/data/share/hydroapps/precip_proc/bin/DHRgather failed with exit code 1
ERROR 2015-09-06 20:33:25,325 [dhrProcess-1] HPEDhrSrv: EDEX - HPE DHR gather did not run successfully and terminated with exit code: 1
