### ISSUE TITLE
macOS 17.1.1-2: Maps with labels do not render

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#181]
After upgrading to 17.1.1-2, map layers with labels (such as Interstates and County Warning Areas) return error messages when displaying. If I reconfigure the map layer to not display a label via context menu, it displays normally. Stack trace below:

```
com.raytheon.uf.viz.core.exception.VizException: Paint error: Error processing map query request for: County Warning Areas:: The resource [County Warning Areas] has been disabled.
	at com.raytheon.uf.viz.core.drawables.AbstractRenderableDisplay.paintResource(AbstractRenderableDisplay.java:632)
	at com.raytheon.uf.viz.core.maps.display.MapRenderableDisplay.paint(MapRenderableDisplay.java:188)
	at com.raytheon.uf.viz.d2d.core.map.D2DMapRenderableDisplay.paint(D2DMapRenderableDisplay.java:220)
	at com.raytheon.viz.ui.panes.VizDisplayPane.glDrawInternal(VizDisplayPane.java:523)
	at com.raytheon.viz.ui.panes.VizDisplayPane.draw(VizDisplayPane.java:477)
	at com.raytheon.viz.ui.panes.DrawCoordinatedPane.draw(DrawCoordinatedPane.java:172)
	at com.raytheon.viz.ui.panes.DrawCoordinatorJob$1.run(DrawCoordinatorJob.java:196)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4033)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:187)
	at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:98)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: com.raytheon.uf.viz.core.exception.VizException: Error processing map query request for: County Warning Areas
	at com.raytheon.uf.viz.core.maps.rsc.DbMapResource.paintInternal(DbMapResource.java:591)
	at com.raytheon.uf.viz.core.rsc.AbstractVizResource.paint(AbstractVizResource.java:510)
	at com.raytheon.uf.viz.core.drawables.AbstractRenderableDisplay.paintResource(AbstractRenderableDisplay.java:629)
	... 35 common frames omitted
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:800)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:590)
	at org.eclipse.swt.opengl.GLCanvas.setCurrent(GLCanvas.java:229)
	at com.raytheon.viz.core.gl.GLContextBridge.makeContextCurrent(GLContextBridge.java:121)
	at com.raytheon.viz.core.gl.internal.GLTarget.getStringsBounds(GLTarget.java:1553)
	at com.raytheon.uf.viz.core.AbstractGraphicsTarget.getStringsBounds(AbstractGraphicsTarget.java:178)
	at com.raytheon.uf.viz.core.maps.rsc.DbMapResource$LabelNode.<init>(DbMapResource.java:151)
	at com.raytheon.uf.viz.core.maps.rsc.DbMapResource$MapQueryJob.processRequest(DbMapResource.java:429)
	at com.raytheon.uf.viz.core.maps.rsc.DbMapResource$MapQueryJob.processRequest(DbMapResource.java:1)
	at com.raytheon.uf.viz.core.maps.jobs.AbstractMapQueryJob.run(AbstractMapQueryJob.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by mjames-upc** [comment]
This is a long-standing OpenGL error on Mac that I don't know when will be fixed.  I've noticed that sometimes if you load another view and add some map overlays, you can then successfully add the CWA boundaries or Interstates (two map resources known to cause this error message).

**Comment by jaredwsmith** [comment]
This is working much more reliably in 17.1.1-3 on macOS High Sierra (10.13.1). There are still issues upon initially starting CAVE (with a five-panel display), but once that is complete, interstates as well as CWA resources display properly.

**Comment by mjames-upc** [comment]
Good to hear that 17.1.1-3 is working better.  I'll be updating the map resources to *not load labels* on macOS to avoid the GL threading error.
