### ISSUE TITLE
MAC 17.1.1-2  Error libjep Module Creation

### ISSUE THREAD

**Issue by live4right** [Unidata/awips2#182]
I installed the new Unidata AWIPS on my MAC OSX. I also input the AWIPS dependency package linked to on the downloads page. I pointed my pydev to my python installation and I received this error: 
# Written by com.raytheon.uf.viz.alertview 1.15.0.201707141022
ERROR 2017-07-15 07:37:36,712 The module libjep could not be found nor created!
java.lang.RuntimeException: The module libjep could not be found nor created!
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.getModule(ModulesManager.java:973)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.getModule(ModulesManager.java:787)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:376)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave# Written by com.raytheon.uf.viz.alertview 1.15.0.201707141022
ERROR 2017-07-15 07:37:36,712 The module libjep could not be found nor created!
java.lang.RuntimeException: The module libjep could not be found nor created!
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.getModule(ModulesManager.java:973)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.getModule(ModulesManager.java:787)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:376)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:256)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:160)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:86)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:261)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)(AbstractAdditionalDependencyInfo.java:256)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:160)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:86)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:261)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
 

Thanks for any help you can provide. Had hoped to finally get some derived parameters working....
Regards,
Carl Berghoff

**Comment by mjames-upc** [comment]
Have you tested that derived parameters work?  I've noticed this error on startup but have still been able to load derived parms, such as Surface Temp and Winds or the Isentropic bundles.

**Comment by live4right** [comment]
I loaded up the GFS Surface Temp and Winds, and everything but the winds loaded. I copied the alertview text. Hope this help.

# Written by com.raytheon.uf.viz.alertview 1.15.0.201707141022
WARN 2017-07-15 11:42:38,480 Error requesting data for GFS 10FHAG Wind Arrows (kts)   15.12   0HR Sat 12:00Z 15-Jul-17: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:209)
	at com.raytheon.viz.grid.rsc.general.GridResource.getData(GridResource.java:84)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestRunner.processOneRequest(GridDataRequestRunner.java:117)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestJobPool$GridDataRequestJob.run(GridDataRequestJobPool.java:120)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecords(GridDataCubeAdapter.java:388)
	at com.raytheon.uf.viz.datacube.AbstractDataCubeAdapter.getRecord(AbstractDataCubeAdapter.java:265)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:142)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getDataRecord(DataCubeContainer.java:130)
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:199)
	... 4 common frames omitted
Caused by: com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:188)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecords(GridDataCubeAdapter.java:385)
	... 8 common frames omitted
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
	at com.raytheon.viz.grid.record.RequestableDataRecord.getDataRecord(RequestableDataRecord.java:121)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:174)
	... 9 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
	at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
	at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:204)
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
	... 11 common frames omitted
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jep.Jep
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:134)
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:108)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.<init>(MasterDerivScript.java:86)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:87)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:1)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
	... 6 common frames omitted
