### ISSUE TITLE
Mac 17.1.1-2 error deserializing class com.raytheon.uf.common.serialization.comm.RequestWrapper

### ISSUE THREAD

**Issue by jntkwx** [Unidata/awips2#183]
I had previously had CAVE version 16 installed, so I uninstalled the old version (removed /Applications/Cave.app and the ~/Library/caveData and ~/Library/CAVE directories). 

I open CAVE 17.1.1-2 on Mac 10.11.6 (El Capitan). I type in Unidata's cloud EDEX server: **edex-cloud.unidata.edu** and leave Site set to the default **BOU** I click Start, and immediately it says:
![screen shot 2017-07-15 at 8 57 34 pm](https://user-images.githubusercontent.com/23132763/28243643-528b3ad6-69a0-11e7-8fab-454b0bf40f5c.png)
Clicking OK, the details of the error are:
> com.raytheon.uf.viz.core.requests.ServerRequestException: Error deserializing class com.raytheon.uf.common.serialization.comm.RequestWrapper
	at com.raytheon.uf.viz.core.requests.ThriftClient.sendRequest(ThriftClient.java:340)
	at com.raytheon.uf.viz.core.requests.ThriftClient.sendRequest(ThriftClient.java:270)
	at com.raytheon.uf.viz.core.comm.ConnectivityManager.checkLocalizationServer(ConnectivityManager.java:150)
	at com.raytheon.uf.viz.core.comm.ConnectivityManager.checkLocalizationServer(ConnectivityManager.java:127)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.validateLocalization(ConnectivityPreferenceDialog.java:562)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.validate(ConnectivityPreferenceDialog.java:526)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.validateAndClose(ConnectivityPreferenceDialog.java:471)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.performOk(ConnectivityPreferenceDialog.java:776)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog$6.widgetSelected(ConnectivityPreferenceDialog.java:426)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4257)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4081)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.open(ConnectivityPreferenceDialog.java:241)
	at com.raytheon.uf.viz.thinclient.localization.ThinClientLocalizationInitializer.setupServers(ThinClientLocalizationInitializer.java:98)
	at com.raytheon.uf.viz.core.localization.LocalizationInitializer.run(LocalizationInitializer.java:76)
	at com.raytheon.uf.viz.thinclient.cave.ThinClientComponent.initializeLocalization(ThinClientComponent.java:148)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:146)
	at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:98)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: com.raytheon.uf.common.serialization.SerializationException: Error deserializing class com.raytheon.uf.common.serialization.comm.RequestWrapper
	at com.raytheon.uf.common.serialization.thrift.ThriftSerializationContext.deserializeMessage(ThriftSerializationContext.java:802)
	at com.raytheon.uf.common.serialization.DynamicSerializationManager.deserialize(DynamicSerializationManager.java:262)
	at com.raytheon.uf.common.serialization.DynamicSerializationManager.deserialize(DynamicSerializationManager.java:246)
	at com.raytheon.uf.edex.requestsrv.serialization.thrift.ThriftStreamSerializer.deserialize(ThriftStreamSerializer.java:77)
	at com.raytheon.uf.edex.requestsrv.serialization.SerializingStreamExecutor.execute(SerializingStreamExecutor.java:106)
	at com.raytheon.uf.edex.requestsrv.serialization.ByteLimitingStreamExecutor.execute(ByteLimitingStreamExecutor.java:76)
	at com.raytheon.uf.edex.requestsrv.http.HttpRequestServiceExecutor.execute(HttpRequestServiceExecutor.java:102)
	at sun.reflect.GeneratedMethodAccessor131.invoke()
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:38)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:116)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:468)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.component.jetty.CamelContinuationServlet.service(CamelContinuationServlet.java:191)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
	at org.apache.thrift.protocol.TBinaryProtocol.readByte(TBinaryProtocol.java:264)
	at com.raytheon.uf.common.serialization.thrift.SelfDescribingBinaryProtocol.readFieldBegin(SelfDescribingBinaryProtocol.java:135)
	at com.raytheon.uf.common.serialization.thrift.ThriftSerializationContext.deserializeField(ThriftSerializationContext.java:1047)
	at com.raytheon.uf.common.serialization.thrift.ThriftSerializationContext.deserializeMessage(ThriftSerializationContext.java:759)
	... 42 more

I had thought the issue might just be with my Mac, since I have connected to Unidata's cloud EDEX server before with this computer, but a friend is also receiving the same error when trying to connect to Unidata's cloud EDEX server, and this is the first time he has installed AWIPS on his Mac.

Thanks for any help you can provide!
Regards,
Jason Kaiser

**Comment by crawld** [comment]
+1

**Comment by NtwkEngineer** [comment]
+2

**Comment by sezick** [comment]
+3

**Comment by mjames-upc** [comment]
Happening with http://www.unidata.ucar.edu/downloads/awips2/awips2-cave-17.1.1-3.dmg ??

**Comment by sezick** [comment]
Yes, I've tried that version and received the error that's detailed above.

I am unable to validate the server on my new Mac, which is running macOS Sierra 10.12.6. 
 However, I am able to successfully install the software and connect to the server on two other Macs which runs older operating systems (El Capitan, Yellowstone).... not sure if it's the OS or something else entirely.

**Comment by mjames-upc** [comment]
Update: this is happening intermittently when a client attempts a warngen/warngenloc query.  I'm not exactly sure where and why this fails, but it puts postgres into recovery mode for a period of time during which CAVE clients can't connect.

```
2017-08-26 14:58:44 UTC 0  :  : LOG:  server process (PID 3004) was terminated by signal 11: Segmentation fault
2017-08-26 14:58:44 UTC 0  :  : DETAIL:  Failed process was running: SELECT AsBinary(the_geom) as the_geom, NAME FROM mapdata.WarnGenLoc WHERE WARNGENLEV = '1' AND ST_Intersects(ST_GeomFromText('POLYGON ((-94.76 29.33, -94.77 29.33, -94.46 29.56, -94.77 29.53, -94.72 29.78, -94.91 29.65, -95.05 29.78, -94.83 29.3, -94.93 29.24, -94.91 29.31, -95 29.25, -96.42 30.81, -95.97 31.09, -95.21 31.06, -94.69 30.49, -94.73 30.49, -94.6 30.12, -94.51 30.11, -94.37 29.55, -94.76 29.33))', 4326), the_geom)
2017-08-26 14:58:44 UTC 0  :  : LOG:  terminating any other active server processes
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : WARNING:  terminating connection because of crash of another server process
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0  :  : LOG:  all server processes terminated; reinitializing
2017-08-26 14:58:44 UTC 0  :  : LOG:  database system was interrupted; last known up at 2017-08-26 14:57:25 UTC
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode
2017-08-26 14:58:44 UTC 0 metadata : 127.0.0.1 : FATAL:  the database system is in recovery mode

```

**Comment by mjames-upc** [comment]
```
2017-08-28 16:30:37 UTC 0  :  : LOG:  server process (PID 16090) was terminated by signal 11: Segmentation fault

Aug 28 16:30:37 edex-cloud kernel: postmaster[16090]: segfault at 1000002a1 ip 00007f09a7a84bf6 sp 00007fffb045fb00 error 4 in libgeos_c.so.1.9.0[7f09a7a72000+2b000]
```

**Comment by klatteri** [comment]
+4, still occurring on latest CAVE/EDEX build

**Comment by AronPryor** [comment]
Any update on this issue?

**Comment by mjames-upc** [comment]
Is this happening while connecting to edex-cloud or to your own EDEX server (since you say EDEX build)?

Does this only occur when using WarnGen?

**Comment by klatteri** [comment]
This is occurring on my own EDEX.

**Comment by jntkwx** [comment]
This occurs for me when initially trying to connect to edex-cloud, when starting AWIPS (i.e. I can't get AWIPS to load at all). I haven't tested it on my own EDEX server.
![screen shot 2018-02-27 at 11 23 17 pm](https://user-images.githubusercontent.com/23132763/36769911-425208fc-1c15-11e8-8955-49007f6403be.png)

**Comment by jgerth** [comment]
We had this issue with CentOS 7. Disable ipv6.

I used sysctl -w. You could also add the following to /etc/sysctl.d:
``net.ipv6.conf.all.disable_ipv6=1``
``net.ipv6.conf.default.disable_ipv6=1``

For Mac, use ``networksetup -setv6off <networkservice>``

**Comment by mjames-upc** [comment]
@jgerth thanks for reporting this.  I'll update the documentation with this info.

**Comment by mattdelashaw** [comment]
+1 no. i'm getting this with both macos and windows 10. both have ip6 off just to validate, unless that was intended to say the edex servers neeed to have ip6 off. you need error lines?

**Comment by mattdelashaw** [comment]
could it have something to do with python versions that were already installed?
`The httplib module has been renamed to http.client in Python 3`

I added cave to the firewall, the serialization seems to have vanished, but now its getting timeout errors when trying to read from the server
```
com.raytheon.uf.viz.core.exception.VizCommunicationException: unable to post request to server
	at com.raytheon.uf.viz.core.requests.ThriftClient.sendRequest(ThriftClient.java:330)
	at com.raytheon.uf.viz.core.requests.ThriftClient.sendRequest(ThriftClient.java:270)
	at com.raytheon.uf.viz.core.comm.ConnectivityManager.checkLocalizationServer(ConnectivityManager.java:150)
	at com.raytheon.uf.viz.core.comm.ConnectivityManager.checkLocalizationServer(ConnectivityManager.java:127)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.validateLocalization(ConnectivityPreferenceDialog.java:562)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.validate(ConnectivityPreferenceDialog.java:526)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog$5.widgetSelected(ConnectivityPreferenceDialog.java:415)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4257)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4081)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at com.raytheon.uf.viz.core.localization.ConnectivityPreferenceDialog.open(ConnectivityPreferenceDialog.java:241)
	at com.raytheon.uf.viz.thinclient.localization.ThinClientLocalizationInitializer.setupServers(ThinClientLocalizationInitializer.java:98)
	at com.raytheon.uf.viz.core.localization.LocalizationInitializer.run(LocalizationInitializer.java:77)
	at com.raytheon.uf.viz.thinclient.cave.ThinClientComponent.initializeLocalization(ThinClientComponent.java:148)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:146)
	at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:98)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: com.raytheon.uf.common.comm.CommunicationException: Error occurred communicating with server: Operation timed out (Read failed).  Hit retry limit, aborting connection.
	at com.raytheon.uf.common.comm.HttpClient.process(HttpClient.java:519)
	at com.raytheon.uf.common.comm.HttpClient.postDynamicSerialize(HttpClient.java:689)
	at com.raytheon.uf.viz.core.requests.ThriftClient.sendRequest(ThriftClient.java:295)
	... 33 more
Caused by: java.net.SocketException: Operation timed out (Read failed)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.raytheon.uf.common.comm.HttpClient.postRequest(HttpClient.java:379)
	at com.raytheon.uf.common.comm.HttpClient.process(HttpClient.java:477)
	... 35 more
```

**Comment by harrisontran** [comment]
+1 on CentOS7 with ipv6 disabled when connecting to edex-cloud.unidata.ucar.edu, and am unable to proceed with AWIPS.

**Comment by mjames-upc** [comment]
@harrisontran did this problem persist, and does it still happen?  Around May 13 we were experiencing problems with EDEX services hanging, still running but not accepting connections or writing to their log files. A clean EDEX reinstall seems to have fixed this.

**Comment by mjames-upc** [comment]
https://www.unidata.ucar.edu/downloads/awips2/awips2-cave-17.1.1-6.dmg is the latest release

**Comment by NaderCHASER** [comment]
**test:test@edex-cloud.allisonhouse.com** might be able to help debug this. Everyone feel free to give this a shot over the next ~week. I'll delete the post after I disable the access.
