### ISSUE TITLE
METAR station plot: Error making point request. No module named DpT

### ISSUE THREAD

**Issue by jntkwx** [Unidata/awips2#185]
CAVE 17.1.1-2 on CentOS 6.9. Clicking on Surface - METAR Station Plots, I get the following error:

```
# Written by com.raytheon.uf.viz.alertview 1.15.0.2017071216
WARN 2017-07-17 15:11:53,984 Error making Point Data request.
com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
	at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:155)
	at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:105)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:168)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:176)
	at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.requestData(PlotModelDataRequestJob.java:257)
	at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.run(PlotModelDataRequestJob.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: jep.JepException: <type 'exceptions.ImportError'>: No module named DpT
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
	at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
	at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:204)
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
	... 7 common frames omitted
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: jep.JepException: <type 'exceptions.ImportError'>: No module named DpT
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: No module named DpT
	at jep.Jep.eval(Jep.java:485)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.executeFunctionInternal(MasterDerivScript.java:125)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.executeFunction(MasterDerivScript.java:92)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptExecutor.execute(MasterDerivScriptExecutor.java:62)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptExecutor.execute(MasterDerivScriptExecutor.java:1)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:233)
	... 6 common frames omitted
Caused by: jep.JepException: <type 'exceptions.ImportError'>: No module named DpT

```

**Comment by jaredwsmith** [comment]
Try renaming your ~/caveData directory to another name, and allow 17.1.1 to recreate the cache. Had to do this on both my Macs and my CentOS 7 install to get things working smoothly.
