### ISSUE TITLE
macOS 17.1.1-2: Time of Arrival / Lead Time tool not functioning

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#188]
The Time of Arrival/Lead Time tool as well as the EAV tool are not functioning in 17.1.1-2 on macOS. This is running the latest macOS Sierra -- 10.12.6. Seeing GL references in the stack trace, so it makes me suspect it's very similar to issues described in #180 and #181.

Here's the trace for Time of Arrival:

```
com.raytheon.uf.viz.core.exception.VizException: Paint error: null:: The resource [Time Of Arrival / Lead Time] has been disabled.
	at com.raytheon.uf.viz.core.drawables.AbstractRenderableDisplay.paintResource(AbstractRenderableDisplay.java:632)
	at com.raytheon.uf.viz.core.maps.display.MapRenderableDisplay.paint(MapRenderableDisplay.java:188)
	at com.raytheon.uf.viz.d2d.core.map.D2DMapRenderableDisplay.paint(D2DMapRenderableDisplay.java:220)
	at com.raytheon.viz.ui.panes.VizDisplayPane.glDrawInternal(VizDisplayPane.java:523)
	at com.raytheon.viz.ui.panes.VizDisplayPane.draw(VizDisplayPane.java:477)
	at com.raytheon.viz.ui.panes.DrawCoordinatedPane.draw(DrawCoordinatedPane.java:172)
	at com.raytheon.viz.ui.panes.DrawCoordinatorJob$1.run(DrawCoordinatorJob.java:196)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4033)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:187)
	at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:98)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.NullPointerException: null
	at com.raytheon.viz.core.gl.internal.GLTarget.getStringsBounds(GLTarget.java:1560)
	at com.raytheon.uf.viz.core.AbstractGraphicsTarget.getStringsBounds(AbstractGraphicsTarget.java:178)
	at com.raytheon.viz.awipstools.ui.layer.TimeOfArrivalLayer.willLeadStateTextFitOnLeft(TimeOfArrivalLayer.java:442)
	at com.raytheon.viz.awipstools.ui.layer.TimeOfArrivalLayer.drawLeadStateString(TimeOfArrivalLayer.java:411)
	at com.raytheon.viz.awipstools.ui.layer.TimeOfArrivalLayer.paintLeadTime(TimeOfArrivalLayer.java:374)
	at com.raytheon.viz.awipstools.ui.layer.TimeOfArrivalLayer.paintInternal(TimeOfArrivalLayer.java:326)
	at com.raytheon.uf.viz.core.rsc.AbstractVizResource.paint(AbstractVizResource.java:510)
	at com.raytheon.uf.viz.core.drawables.AbstractRenderableDisplay.paintResource(AbstractRenderableDisplay.java:629)
	... 35 common frames omitted
```

**Comment by jaredwsmith** [comment]
This now appears to be working on macOS High Sierra (10.13.1) with AWIPS 17.1.1-3 on macOS. Closing this out.
