### ISSUE TITLE
 Error executing QlServerRequest / ERROR: relation "afoslookup" does not exist

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#192]
```
ERROR 2017-08-29 21:44:01,259 8433 [qtp858848584-1868] ThriftSrvRequestLogger: EDEX: ThriftSrvRequestLogger - Error executing request: Request[User@10.0.0.8:CAVE:4188:1][d205934e-8b97-463c-813d-cb2ac328623b] QlServerRequest:
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:88)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2062)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1859)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)

...
Caused by: org.postgresql.util.PSQLException: ERROR: relation "afoslookup" does not exist
  Position: 17
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)

```

**Comment by mjames-upc** [comment]
afoslookup was removed in 17.1.1, these error msgs are remnants from clients before that release.
