### ISSUE TITLE
w/out numpy installed GribDecoder.py doesn't find awips2-python-numpy via Jep

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#195]
```
INFO  2017-10-09 20:29:29,262 1855 [Ingest.GribDecode-7] GribDecoder: EDEX - Decoding file: /awips2/data_store/grid/external/nam.t12z.conusnest.hiresf00.tm00.grib2
ImportError: numpy.core.multiarray failed to import
ERROR 2017-10-09 20:29:29,312 1856 [Ingest.GribDecode-1] PythonDecoderFactory: Error instantiating python decoder GribDecoder from jar /awips2/edex/lib/plugins/com.raytheon.edex.plugin.grib.jar
jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: numpy.core.multiarray failed to import
	at jep.Jep.eval(Jep.java:485)
	at com.raytheon.uf.common.python.PythonScript.internalExecute(PythonScript.java:230)
	at com.raytheon.uf.common.python.PythonScript.execute(PythonScript.java:278)
	at com.raytheon.uf.common.python.PythonScript.execute(PythonScript.java:258)
	at com.raytheon.uf.edex.python.decoder.PythonDecoderFactory.makePythonDecoder(PythonDecoderFactory.java:114)
	at com.raytheon.uf.edex.python.decoder.PythonDecoder.decode(PythonDecoder.java:97)
	at com.raytheon.edex.plugin.grib.Grib2Decoder.decode(Grib2Decoder.java:67)
	at com.raytheon.edex.plugin.grib.GribDecoder.process(GribDecoder.java:86)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:102)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:63)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:68)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1164)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1156)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: jep.JepException: <type 'exceptions.ImportError'>: numpy.core.multiarray failed to import
	at /awips2/edex/data/utility/common_static/base/python/DecoderInterface.loadModule(DecoderInterface.py:45)

```

**Comment by mjames-upc** [comment]
resolved by requiring atlas as an rpm dep.
