### ISSUE TITLE
Error occurred purging orphans

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#204]
```
ERROR 2017-11-02 17:15:15,301 6445 [Camel (clusteredpurgeContext) thread #4 - timer://purgeOrphan] purge: Exchange[ExchangePattern: InOnly, BodyType: null, CaughtExceptionType: com.raytheon.uf.common.dataplugin.PluginException, CaughtExceptionMessage: Error occurred purging orphans. , StackTrace: com.raytheon.uf.common.dataplugin.PluginException: Error occurred purging orphans. 
	at com.raytheon.uf.edex.database.plugin.PluginDao.purgeOrphanedData(PluginDao.java:1288)
	at com.raytheon.uf.edex.purgesrv.PurgeManager.purgeOrphanedData(PurgeManager.java:475)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:68)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:95)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:192)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.raytheon.uf.common.datastorage.StorageException: Error deserializing request: Traceback (most recent call last):
   File "/awips2/python/lib/python2.7/site-packages/pypies/handlers.py", line 78, in pypies_response
    obj = dynamicserialize.deserialize(data)
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/__init__.py", line 58, in deserialize
    return dsm.deserializeBytes(bytes)
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/DynamicSerializationManager.py", line 52, in deserializeBytes
    obj = self._deserialize(ctx)
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/DynamicSerializationManager.py", line 47, in _deserialize
    return ctx.deserializeMessage()
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/ThriftSerializationContext.py", line 179, in deserializeMessage
    clz = dsObjTypes[name]
 KeyError: 'com.raytheon.uf.common.pypies.request.DeleteOrphansRequest'

	at com.raytheon.uf.common.pypies.PyPiesDataStore.sendRequest(PyPiesDataStore.java:305)
	at com.raytheon.uf.common.pypies.PyPiesDataStore.sendRequest(PyPiesDataStore.java:279)
	at com.raytheon.uf.common.pypies.PyPiesDataStore.deleteOrphanData(PyPiesDataStore.java:463)
	at com.raytheon.uf.edex.database.plugin.PluginDao.purgeOrphanedData(PluginDao.java:1286)
	... 26 more
]

```

**Comment by mjames-upc** [comment]
duplicate of #86
