### ISSUE TITLE
EDEX Error During Start-up

### ISSUE THREAD

**Issue by WxmanJ** [Unidata/awips2#215]
OS: CentOS7

Issue encountered during start-up:
```
ERROR 2018-03-22 17:01:01,824 2052 [EDEXMain] Main: Error occurred during startup: 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.raytheon.uf.edex.esb.Main.main(Main.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:53)
	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:36)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gfeActivationAsyncIngest' defined in class path resource [res/spring/gfe-spring.xml]: Cannot resolve reference to bean 'gfeSiteActivation' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gridcoverageRegistered' defined in class path resource [res/spring/gridcoverage-common.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.lang.Object]: Factory method 'register' threw exception; nested exception is com.raytheon.uf.common.util.registry.RegistryException: Plugin com.raytheon.uf.common.gridcoverage failed during registration
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:444)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:179)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at com.raytheon.uf.edex.esb.camel.Executor.start(Executor.java:181)
	... 11 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gridcoverageRegistered' defined in class path resource [res/spring/gridcoverage-common.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.lang.Object]: Factory method 'register' threw exception; nested exception is com.raytheon.uf.common.util.registry.RegistryException: Plugin com.raytheon.uf.common.gridcoverage failed during registration
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 28 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.lang.Object]: Factory method 'register' threw exception; nested exception is com.raytheon.uf.common.util.registry.RegistryException: Plugin com.raytheon.uf.common.gridcoverage failed during registration
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 45 common frames omitted
Caused by: com.raytheon.uf.common.util.registry.RegistryException: Plugin com.raytheon.uf.common.gridcoverage failed during registration
	at com.raytheon.uf.edex.database.DatabasePluginRegistry.register(DatabasePluginRegistry.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 46 common frames omitted
Caused by: com.raytheon.uf.common.dataplugin.PluginException: com.raytheon.uf.common.dataplugin.PluginException: Error occurred exporting schema, sql [create table gridcoverage (dtype varchar(31) not null, id int4 not null, crs varchar(2047), dx float8, dy float8, firstgridpointcorner varchar(255), the_geom geometry, la1 float8, lo1 float8, name varchar(255), nx int4, ny int4, spacingunit varchar(255), latin1 float8, latin2 float8, lov float8, majoraxis float8, minoraxis float8, lad float8, la2 float8, latin float8, lo2 float8, primary key (id))]
	at com.raytheon.uf.edex.database.plugin.SchemaManager.pluginAdded(SchemaManager.java:211)
	at com.raytheon.uf.edex.database.DatabasePluginRegistry.register(DatabasePluginRegistry.java:91)
	... 51 common frames omitted
Caused by: com.raytheon.uf.common.dataplugin.PluginException: Error occurred exporting schema, sql [create table gridcoverage (dtype varchar(31) not null, id int4 not null, crs varchar(2047), dx float8, dy float8, firstgridpointcorner varchar(255), the_geom geometry, la1 float8, lo1 float8, name varchar(255), nx int4, ny int4, spacingunit varchar(255), latin1 float8, latin2 float8, lov float8, majoraxis float8, minoraxis float8, lad float8, la2 float8, latin float8, lo2 float8, primary key (id))]
	at com.raytheon.uf.edex.database.plugin.SchemaManager.exportSchema(SchemaManager.java:401)
	at com.raytheon.uf.edex.database.plugin.SchemaManager.pluginAdded(SchemaManager.java:193)
	... 52 common frames omitted
Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:124)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:189)
	at org.hibernate.engine.query.spi.NativeSQLQueryPlan.performExecuteUpdate(NativeSQLQueryPlan.java:204)
	at org.hibernate.internal.SessionImpl.executeNativeUpdate(SessionImpl.java:1238)
	at org.hibernate.internal.SQLQueryImpl.executeUpdate(SQLQueryImpl.java:401)
	at com.raytheon.uf.edex.database.dao.CoreDao$18.doInTransaction(CoreDao.java:1058)
	at com.raytheon.uf.edex.database.dao.CoreDao$18.doInTransaction(CoreDao.java:1)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.raytheon.uf.edex.database.dao.CoreDao.executeSQLUpdate(CoreDao.java:1050)
	at com.raytheon.uf.edex.database.dao.CoreDao.executeSQLUpdate(CoreDao.java:1014)
	at com.raytheon.uf.edex.database.plugin.SchemaManager.exportSchema(SchemaManager.java:398)
	... 53 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: type "geometry" is only a shell
  Position: 159
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:562)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:186)
	... 62 common frames omitted
INFO  2018-03-22 17:01:01,830 2053 [Thread-2] Executor: 
**************************************************
* EDEX ESB is shutting down                      *
**************************************************
INFO  2018-03-22 17:01:01,832 2054 [Thread-2] Executor: Contexts never started, skipping context shutdown
INFO  2018-03-22 17:01:01,854 2055 [Thread-2] Executor: 
**************************************************
* EDEX ESB is shut down                          *
* Total time to shutdown: 2ms
* EDEX ESB uptime: 9.7s
```

**Comment by mjames-upc** [comment]
Most likely the fix is to manually install or reinstall the awips2-edex-gfe RPM. Regardless, I can not reproduce this error on standard el6 and el7 installs, so will mark this as closed.
