### ISSUE TITLE
Error trying to send product to workstation

### ISSUE THREAD

**Issue by Thunderbuddy01** [Unidata/awips2#217]
I keep getting this error when trying to create a warning product:

java.lang.NullPointerException: null
	at com.raytheon.viz.warngen.comm.WarningSender.setTextWarngenDisplay(WarningSender.java:143)
	at com.raytheon.viz.warngen.gui.WarngenDialog$23.run(WarngenDialog.java:1267)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by FrostTheFox** [comment]
Same error occuring here in addition to failed to connect to JMS server. Fresh CentOS 7 install.

**Comment by Thunderbuddy01** [comment]
@mjames-upc What should we do with the commit that you posted?

**Comment by mjames-upc** [comment]
Wait for https://github.com/Unidata/awips2/issues/223 to be closed after which I will have the 17.1.1-6 DMG release available.
