### ISSUE TITLE
jep.JepException: <type 'exceptions.ImportError'>: No module named fips2cities

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#234]
```
INFO  2018-07-10 15:05:59,142 1143 [pool-4-thread-1] CombinationsFileMaker: Combinations Files generation phase
INFO  2018-07-10 15:05:59,173 1144 [pool-4-thread-1] EdexLogStream: definitionDir /awips2/edex/data/utility/cave_static/configured/OAX/gfe/userPython/textUtilities/regular 
INFO  2018-07-10 15:05:59,182 1145 [pool-4-thread-1] CombinationsFileMaker: Combinations Files generation time: 40 ms
INFO  2018-07-10 15:05:59,184 1146 [pool-4-thread-1] AreaDictionaryMaker: EDEX - Area Dictionary generation phase
WARN  2018-07-10 15:05:59,188 1147 [pool-4-thread-1] AreaDictionaryMaker: EDEX - No county edit area attributes found. Not generating fips2cites.
WARN  2018-07-10 15:05:59,188 1148 [pool-4-thread-1] AreaDictionaryMaker: EDEX - No zone edit area attributes found. Not generating zones2cites.
ERROR 2018-07-10 15:05:59,221 1149 [pool-4-thread-1] AreaDictionaryMaker: EDEX - Error generating area dictionary
jep.JepException: <type 'exceptions.ImportError'>: No module named fips2cities
	at /awips2/edex/data/utility/common_static/base/gfe/python/createAreaDictionary.<module>(createAreaDictionary.py:53) ~[na:na]
	at jep.Jep.run(Native Method) ~[jep-3.7.1.jar:na]
	at jep.Jep.runScript(Jep.java:506) ~[jep-3.7.1.jar:na]
	at jep.Jep.runScript(Jep.java:482) ~[jep-3.7.1.jar:na]
	at com.raytheon.uf.common.python.PythonInterpreter.initializeJep(PythonInterpreter.java:159) ~[com.raytheon.uf.common.python.jar:na]
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:134) ~[com.raytheon.uf.common.python.jar:na]
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:87) ~[com.raytheon.uf.common.python.jar:na]
	at com.raytheon.uf.common.python.PythonScript.<init>(PythonScript.java:95) ~[com.raytheon.uf.common.python.jar:na]
	at com.raytheon.uf.common.python.PythonScript.<init>(PythonScript.java:150) ~[com.raytheon.uf.common.python.jar:na]
	at com.raytheon.edex.plugin.gfe.textproducts.AreaDictionaryMaker.genAreaDictionary(AreaDictionaryMaker.java:222) ~[com.raytheon.edex.plugin.gfe.jar:na]
	at com.raytheon.edex.plugin.gfe.reference.MapManager.<init>(MapManager.java:280) [com.raytheon.edex.plugin.gfe.jar:na]
	at com.raytheon.edex.plugin.gfe.server.IFPServer.init(IFPServer.java:275) [com.raytheon.edex.plugin.gfe.jar:na]
	at com.raytheon.edex.plugin.gfe.server.IFPServer.activateServer(IFPServer.java:152) [com.raytheon.edex.plugin.gfe.jar:na]
	at com.raytheon.edex.plugin.gfe.config.GFESiteActivation.internalActivateSite(GFESiteActivation.java:408) [com.raytheon.edex.plugin.gfe.jar:na]
	at com.raytheon.edex.plugin.gfe.config.GFESiteActivation.activateSite(GFESiteActivation.java:261) [com.raytheon.edex.plugin.gfe.jar:na]
	at com.raytheon.uf.edex.site.SiteAwareRegistry$1.run(SiteAwareRegistry.java:135) [com.raytheon.uf.edex.site.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
INFO  2018-07-10 15:05:59,221 1150 [pool-4-thread-1] AreaDictionaryMaker: EDEX - Area Dictionary generation time: 36 ms
INFO  2018-07-10 15:05:59,221 1151 [pool-4-thread-1] MapManager: EDEX - MapManager ready.
INFO  2018-07-10 15:05:59,221 1152 [pool-4-thread-1] MapManager: EDEX - MapCreation time: 898 ms
INFO  2018-07-10 15:05:59,255 1153 [pool-4-thread-1] TopoDatabaseManager: EDEX - Topography Manager started for OAX

```

**Comment by mjames-upc** [comment]
from https://github.com/Unidata/awips2/blob/unidata_18.1.1/edexOsgi/com.raytheon.edex.plugin.gfe/src/com/raytheon/edex/plugin/gfe/textproducts/AreaDictionaryMaker.java#L173

```
        public void genAreaDictionary(String siteID,
            Map<String, List<Map<String, Object>>> editAreaAttrs) {
        ...

        LocalizationContext configuredCtx = pathMgr.getContext(
                LocalizationContext.LocalizationType.COMMON_STATIC,
                LocalizationContext.LocalizationLevel.CONFIGURED);
        configuredCtx.setContextName(siteID);

        List<Map<String, Object>> countyAttrs = editAreaAttrs.get("Counties");
        List<Map<String, Object>> zoneAttrs = editAreaAttrs.get("Zones");

        if (countyAttrs != null) {
            genFips2Cities(configuredCtx, countyAttrs);
        } else {
            statusHandler.warn(
                    "No county edit area attributes found. Not generating fips2cites.");
        }

        if (zoneAttrs != null) {
            genZones2Cities(configuredCtx, zoneAttrs);
        } else {
            statusHandler.warn(
                    "No zone edit area attributes found. Not generating zones2cites.");
        }
        ...


```




```
    private void genFips2Cities(LocalizationContext context,
            List<Map<String, Object>> attributes) {
        genArea2Cities(context, attributes, "fips2cities.py", "fipsdata",
                "FIPS", 'C', FIPS_CITY_QUERY);
    }

```

**Comment by mjames-upc** [comment]
I believe this is a result of #229
