### ISSUE TITLE
ContextManager: Failed to start context:  Endpoint [metarToShef] has no defined consumers

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#239]
```
ERROR 2018-07-13 18:26:33,126 4329 [Camel (clusteredCamel) thread #0 - timer://monitorClusterContexts] ContextManager: EDEX - Failed to start context edexStats-camel
javax.naming.ConfigurationException: Internal Routing Endpoint [metarToShef] has no defined consumers.  This is endpoint is used in contexts [persist-camel]
        at com.raytheon.uf.edex.esb.camel.context.ContextDependencyMapping.populateDependencyMapping(ContextDependencyMapping.java:223) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        at com.raytheon.uf.edex.esb.camel.context.ContextDependencyMapping.<init>(ContextDependencyMapping.java:97) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        at com.raytheon.uf.edex.esb.camel.context.ContextManager.getDependencyMapping(ContextManager.java:244) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        at com.raytheon.uf.edex.esb.camel.context.DependencyContextStateManager.startContext(DependencyContextStateManager.java:111) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        at com.raytheon.uf.edex.esb.camel.context.ContextManager.checkClusteredContexts(ContextManager.java:551) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:458) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:289) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:262) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:178) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:69) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:68) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:192) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76) [camel-core-2.18.3.jar:2.18.3]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_101]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_101]
```

**Comment by mjames-upc** [comment]
the first instance after startup 

```
INFO  2018-07-13 18:26:32,238 4326 [Ingest.obs-1] Ingest: EDEX: Ingest - obs:: /awips2/data_store/metar/SANA14_KAWN_131700_4960680 processed in: 0.1690 (sec) Latency: 259.1060 (sec)
WARN  2018-07-13 18:26:32,246 4327 [Ingest.obs-1] PluginNotifier: EDEX - Unable to send notification data to direct-vm:metarToShef
com.raytheon.uf.edex.core.EdexException: Error sending asynchronous message: [/obs/2018-07-13_17:15:00.0/METAR/null/KOSC/44.46/-83.4, /obs/2018-07-13_16:58:00.0/METAR/COR/KSKA/47.62/-117.65] to uri: direct-vm:metarToShef
        at com.raytheon.uf.edex.esb.camel.MessageProducer.sendAsyncUri(MessageProducer.java:170) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        at com.raytheon.uf.edex.ingest.notification.router.PdoRouter.sendImmediateData(PdoRouter.java:86) ~[com.raytheon.uf.edex.ingest.jar:na]
        at com.raytheon.uf.edex.ingest.notification.PluginNotifier.notify(PluginNotifier.java:412) ~[com.raytheon.uf.edex.ingest.jar:na]
        at sun.reflect.GeneratedMethodAccessor188.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:458) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:289) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:262) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:178) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:69) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.directvm.DirectVmProcessor.process(DirectVmProcessor.java:57) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.directvm.DirectVmProducer.process(DirectVmProducer.java:68) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:116) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.directvm.DirectVmProcessor.process(DirectVmProcessor.java:57) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.directvm.DirectVmProducer.process(DirectVmProducer.java:68) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:145) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:116) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:63) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:68) [camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439) [com.raytheon.uf.edex.esb.camel.jar:na]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112) [camel-jms-2.18.3.jar:2.18.3]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:313) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:251) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1164) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1156) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053) [spring-jms-4.2.9.RELEASE.jar:4.2.9.RELEASE]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-js-104-119-jetstream-cloud-org-37198-1531505637113-6-1902]
        at org.apache.camel.util.ObjectHelper.wrapCamelExecutionException(ObjectHelper.java:1795) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.util.ExchangeHelper.extractResultBody(ExchangeHelper.java:677) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:515) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:157) ~[camel-core-2.18.3.jar:2.18.3]
        at com.raytheon.uf.edex.esb.camel.MessageProducer.sendAsyncUri(MessageProducer.java:167) ~[com.raytheon.uf.edex.esb.camel.jar:na]
        ... 66 common frames omitted
Caused by: org.apache.camel.component.directvm.DirectVmConsumerNotAvailableException: No consumers available on endpoint: direct-vm://metarToShef. Exchange[ID-js-104-119-jetstream-cloud-org-37198-1531505637113-6-1902]
        at org.apache.camel.component.directvm.DirectVmProducer.process(DirectVmProducer.java:45) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) [camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:529) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.ProducerCache$1.doInProducer(ProducerCache.java:497) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:365) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:497) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:242) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:148) ~[camel-core-2.18.3.jar:2.18.3]
        at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:156) ~[camel-core-2.18.3.jar:2.18.3]
        ... 67 common frames omitted

```

**Comment by mjames-upc** [comment]
Thinking this could be a result of errors w metar2shef during spring initialization, so will do a clean groupremove and groupinstall with the latest RPM build after bfa6f10
