### ISSUE TITLE
McidasSatelliteDecoder: BufferUnderflowException

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#244]
```
ERROR 2018-07-24 20:04:41,207 6608 [Ingest.Satellite.Mcidas-1] sat: Exchange[ExchangePattern: InOnly, BodyType: java.io.File, CaughtExceptionType: java.nio.BufferUnderflowException, CaughtExceptionMessage: null, StackTrace: java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
        at java.nio.ByteBuffer.get(ByteBuffer.java:715)
        at com.raytheon.uf.edex.plugin.satellite.mcidas.McidasSatelliteDecoder.decodeMcidasArea(McidasSatelliteDecoder.java:295)
        at com.raytheon.uf.edex.plugin.satellite.mcidas.McidasSatelliteDecoder.decode(McidasSatelliteDecoder.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:458)
        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:289)
        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:262)
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:178)
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:69)
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439)
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:63)
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439)
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113)
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84)
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
        at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:68)
        at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:439)
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
        at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:313)
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:251)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1164)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1156)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
]

```

**Comment by mjames-upc** [comment]
```
metadata=> select distinct(physicalelement) from satellite where source = 'McIDAS';
        physicalelement         
--------------------------------
 Imager Visible
 Imager 11 micron IR
 Imager 13 micron IR
 Imager 3.5-4.0 micron IR (Fog)
 Imager 6.7-6.5 micron IR (WV)
(5 rows)

metadata=> select distinct(sectorid) from satellite where source = 'McIDAS';
 sectorid  
-----------
 GOES-West
(1 row)

metadata=> select distinct(creatingentity) from satellite where source = 'McIDAS';
 creatingentity 
----------------
 GOES-15(P)
(1 row)
```
