### ISSUE TITLE
Derived Parameter Error with Build 18.1 At Least For Me......

### ISSUE THREAD

**Issue by live4right** [Unidata/awips2#261]
Good morning,

I have been getting very frustrated trying to figure out why, with jep installed, as well as the environment variables for Python, and Java being entered, I am receiving this error, when loading up isobaric wind data and derived parameters. Can you explain what all of that code means there and how to finally fix it once and for all?  I am positive I installed everything according to the instructions. I can see that even though jep was installed through python there is a jep.dll and those files, but no jep.init.  Thanks and have a great day!  On a happier note I really like the GOES-16 and GLM.

--Carl

com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:212)
	at com.raytheon.viz.grid.rsc.general.GridResource.getData(GridResource.java:84)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestRunner.processOneRequest(GridDataRequestRunner.java:117)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestJobPool$GridDataRequestJob.run(GridDataRequestJobPool.java:120)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecordsAsMap(GridDataCubeAdapter.java:424)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:145)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getDataRecord(DataCubeContainer.java:130)
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:203)
	... 4 common frames omitted
Caused by: com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:201)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecordsAsMap(GridDataCubeAdapter.java:421)
	... 7 common frames omitted
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
	at com.raytheon.viz.grid.record.RequestableDataRecord.getDataRecord(RequestableDataRecord.java:110)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:188)
	... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: C:\ProgramData\Miniconda3\Lib\site-packages\jep\jep.dll: The device is not ready
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
	at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
	at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:205)
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
	... 10 common frames omitted
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: C:\ProgramData\Miniconda3\Lib\site-packages\jep\jep.dll: The device is not ready
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.UnsatisfiedLinkError: C:\ProgramData\Miniconda3\Lib\site-packages\jep\jep.dll: The device is not ready
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at jep.LibraryLocator.searchPackageDir(LibraryLocator.java:213)
	at jep.LibraryLocator.searchSitePackages(LibraryLocator.java:131)
	at jep.LibraryLocator.findJepLibrary(LibraryLocator.java:276)
	at jep.MainInterpreter.initialize(MainInterpreter.java:123)
	at jep.MainInterpreter.getMainInterpreter(MainInterpreter.java:97)
	at jep.Jep.<init>(Jep.java:232)
	at jep.Jep.<init>(Jep.java:228)
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:133)
	at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:102)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.<init>(MasterDerivScript.java:98)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:92)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:1)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
	... 6 common frames omitted

                                                      Here is yet another code I have: 

java.lang.RuntimeException: The python client still hasn't connected back to the eclipse java vm (will retry...)
	at org.python.pydev.core.log.Log.log(Log.java:54)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.startIt(AbstractShell.java:334)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:232)
	at org.python.pydev.editor.codecompletion.shell.ShellsContainer.getServerShell(ShellsContainer.java:165)
	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getServerShell(AbstractShell.java:222)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:372)
	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:176)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:332)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:371)
	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:256)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:154)
	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:80)
	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:390)
	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:261)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by live4right** [comment]
Did more experimenting unistalled miniconda and the dependent packages as well as AWIPS and reinstalled everything, now here is the error I receive with derived parameters:

com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:212)
	at com.raytheon.viz.grid.rsc.general.GridResource.getData(GridResource.java:84)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestRunner.processOneRequest(GridDataRequestRunner.java:117)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestJobPool$GridDataRequestJob.run(GridDataRequestJobPool.java:120)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecordsAsMap(GridDataCubeAdapter.java:424)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:145)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getDataRecord(DataCubeContainer.java:130)
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:203)
	... 4 common frames omitted
Caused by: com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:201)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecordsAsMap(GridDataCubeAdapter.java:421)
	... 7 common frames omitted
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
	at com.raytheon.viz.grid.record.RequestableDataRecord.getDataRecord(RequestableDataRecord.java:110)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:188)
	... 8 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: <class 'TypeError'>: '<=' not supported between instances of 'jep.PyJObject' and 'int'
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
	at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
	at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:205)
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
	... 10 common frames omitted
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: <class 'TypeError'>: '<=' not supported between instances of 'jep.PyJObject' and 'int'
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: jep.JepException: <class 'TypeError'>: '<=' not supported between instances of 'jep.PyJObject' and 'int'
	at <string>.<module>(<string>:1)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:507)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.setDataRecordArg(MasterDerivScript.java:349)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.evaluateArgument(MasterDerivScript.java:201)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.evaluateArgument(MasterDerivScript.java:187)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.executeFunctionInternal(MasterDerivScript.java:127)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.executeFunction(MasterDerivScript.java:104)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptExecutor.execute(MasterDerivScriptExecutor.java:62)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptExecutor.execute(MasterDerivScriptExecutor.java:1)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:233)
	... 6 common frames omitted
