### ISSUE TITLE
Cannot load CAVE 18.1.1

### ISSUE THREAD

**Issue by ld7591** [Unidata/awips2#267]
OS is Windows 10 / Java 8 - 191 (64-bit).  The opening scripting hangs with the error message "error instantiating workbench: null" The metadata log records the following:

!ENTRY org.eclipse.osgi 4 0 2018-10-18 10:13:51.831
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: Could not initialize class com.raytheon.uf.common.jms.notification.JmsNotificationManager
	at com.raytheon.uf.viz.core.notification.jobs.NotificationManagerJob.<init>(NotificationManagerJob.java:112)
	at com.raytheon.uf.viz.core.notification.jobs.NotificationManagerJob.getInstance(NotificationManagerJob.java:72)
	at com.raytheon.uf.viz.core.notification.jobs.NotificationManagerJob.disconnect(NotificationManagerJob.java:213)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.cleanup(CAVEApplication.java:199)
	at com.raytheon.viz.ui.personalities.awips.AbstractAWIPSComponent.cleanup(AbstractAWIPSComponent.java:98)
	at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:184)
	at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:99)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by ld7591** [comment]
figured it out myself.  Went to cavedata/.metadata and deleted the entire .metadata file.  CAVE 18.1.1 now loads.
