### ISSUE TITLE
WarnGen not launching?

### ISSUE THREAD

**Issue by reverdlive** [Unidata/awips2#338]
My WarnGen on AWIPS II isn’t working. In the console log, I see “error in initializing geometries. I am set to my radar, KDIX and have set it to 0.5Z+SRM8. I am running it on a Windows 10 Home Laptop. Also, when I generate a watch, it says no counties are selected and won’t let me select any. Any help would be appreciated!

(I had to change the file manually from read-only to editable. Here is my config for WarnGen): 

<?xml version="1.0"?>

-<configuration>

<warngenOfficeShort>Mount Holly NJ</warngenOfficeShort>

<warngenOfficeLoc>Mount Holly NJ</warngenOfficeLoc>

<backupCWAs>OKX</backupCWAs>

<siteNode>DIX</siteNode>

<defaultTemplate>severeThunderstormWarning</defaultTemplate>

<mainWarngenProducts>Tornado/tornadoWarning,Severe Thunderstorm/severeThunderstormWarning,Severe Weather Statement/severeWeatherStatement,Significant Weather Advisory/significantWeatherAdvisory,Flash Flood Warning/flashFloodWarning</mainWarngenProducts>

<otherWarngenProducts>Flash Flood Statement/flashFloodWarningFollowup,Non-Convective FFW (incl. Dam Break)/nonConvectiveFlashFloodWarning,Non-Convective Flash Flood Statement/nonConvectiveFlashFloodWarningFollowup,Areal Flood Warning/arealFloodWarning,Areal Flood Warning Followup/arealFloodWarningFollowup,Areal Flood Advisory/arealFloodAdvisory,Areal Flood Advisory Followup/arealFloodAdvisoryFollowup,Special Weather Statement/specialWeatherStatement,Short Term Forecast/shortTermForecast</otherWarngenProducts>

-<gridSpacing>

<nx>600</nx>

<ny>600</ny>

<keepAspectRatio>true</keepAspectRatio>

</gridSpacing>

</configuration>

(Here is the error:) 

14:05:13.770 [main] WARN CaveLogger - Error in initializing geometries.
java.lang.NullPointerException: null
        at com.raytheon.viz.warngen.gui.WarngenLayer.updateGeoData(WarngenLayer.java:2228)
        at com.raytheon.viz.warngen.gui.WarngenLayer.loadGeodataForConfiguration(WarngenLayer.java:2149)
        at com.raytheon.viz.warngen.gui.WarngenLayer.init(WarngenLayer.java:2086)
        at com.raytheon.viz.warngen.gui.WarngenLayer.setTemplateName(WarngenLayer.java:2057)
        at com.raytheon.viz.warngen.gui.WarngenLayer.<init>(WarngenLayer.java:1520)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.raytheon.uf.viz.core.rsc.tools.GenericToolsResourceData.construct(GenericToolsResourceData.java:119)
        at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.getResource(AbstractGenericToolAction.java:107)
        at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:91)
        at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:1)
        at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.execute(AbstractGenericToolAction.java:76)
        at com.raytheon.viz.warngen.gui.WarngenAction.execute(WarngenAction.java:98)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:174)
        at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:99)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
14:05:13.772 [main] WARN CaveLogger - Failed to initalized map tool
com.raytheon.uf.viz.core.exception.VizException: Failed to initialize a Tool Resource
        at com.raytheon.uf.viz.core.rsc.tools.GenericToolsResourceData.construct(GenericToolsResourceData.java:138)
        at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.getResource(AbstractGenericToolAction.java:107)
        at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:91)
        at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:1)
        at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.execute(AbstractGenericToolAction.java:76)
        at com.raytheon.viz.warngen.gui.WarngenAction.execute(WarngenAction.java:98)
        at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
        at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
        at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:174)
        at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:99)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.raytheon.uf.viz.core.rsc.tools.GenericToolsResourceData.construct(GenericToolsResourceData.java:119)
        ... 49 common frames omitted
Caused by: java.lang.IllegalArgumentException: GeospatialDataAccessor must have geospatial data, geoData is null.
        at com.raytheon.viz.warngen.gui.WarngenLayer$GeospatialDataAccessor.<init>(WarngenLayer.java:349)
        at com.raytheon.viz.warngen.gui.WarngenLayer.init(WarngenLayer.java:2091)
        at com.raytheon.viz.warngen.gui.WarngenLayer.setTemplateName(WarngenLayer.java:2057)
        at com.raytheon.viz.warngen.gui.WarngenLayer.<init>(WarngenLayer.java:1520)
        ... 54 common frames omitted

**Comment by reverdlive** [comment]
> My WarnGen on AWIPS II isn’t working. In the console log, I see “error in initializing geometries. I am set to my radar, KDIX and have set it to 0.5Z+SRM8. I am running it on a Windows 10 Home Laptop. Also, when I generate a watch, it says no counties are selected and won’t let me select any. Any help would be appreciated!
> 
> (I had to change the file manually from read-only to editable. Here is my config for WarnGen):
> 
> -
> 
> Mount Holly NJ
> 
> Mount Holly NJ
> 
> OKX
> 
> DIX
> 
> severeThunderstormWarning
> 
> Tornado/tornadoWarning,Severe Thunderstorm/severeThunderstormWarning,Severe Weather Statement/severeWeatherStatement,Significant Weather Advisory/significantWeatherAdvisory,Flash Flood Warning/flashFloodWarning
> 
> Flash Flood Statement/flashFloodWarningFollowup,Non-Convective FFW (incl. Dam Break)/nonConvectiveFlashFloodWarning,Non-Convective Flash Flood Statement/nonConvectiveFlashFloodWarningFollowup,Areal Flood Warning/arealFloodWarning,Areal Flood Warning Followup/arealFloodWarningFollowup,Areal Flood Advisory/arealFloodAdvisory,Areal Flood Advisory Followup/arealFloodAdvisoryFollowup,Special Weather Statement/specialWeatherStatement,Short Term Forecast/shortTermForecast
> 
> -
> 
> 600
> 
> 600
> 
> true
> 
> (Here is the error:)
> 
> 14:05:13.770 [main] WARN CaveLogger - Error in initializing geometries.
> java.lang.NullPointerException: null
> at com.raytheon.viz.warngen.gui.WarngenLayer.updateGeoData(WarngenLayer.java:2228)
> at com.raytheon.viz.warngen.gui.WarngenLayer.loadGeodataForConfiguration(WarngenLayer.java:2149)
> at com.raytheon.viz.warngen.gui.WarngenLayer.init(WarngenLayer.java:2086)
> at com.raytheon.viz.warngen.gui.WarngenLayer.setTemplateName(WarngenLayer.java:2057)
> at com.raytheon.viz.warngen.gui.WarngenLayer.(WarngenLayer.java:1520)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> at java.lang.reflect.Constructor.newInstance(Unknown Source)
> at com.raytheon.uf.viz.core.rsc.tools.GenericToolsResourceData.construct(GenericToolsResourceData.java:119)
> at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.getResource(AbstractGenericToolAction.java:107)
> at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:91)
> at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:1)
> at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.execute(AbstractGenericToolAction.java:76)
> at com.raytheon.viz.warngen.gui.WarngenAction.execute(WarngenAction.java:98)
> at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
> at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
> at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
> at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
> at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
> at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
> at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
> at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
> at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
> at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
> at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
> at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
> at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
> at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
> at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
> at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
> at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
> at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
> at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
> at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
> at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
> at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:174)
> at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:99)
> at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
> at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
> at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
> 14:05:13.772 [main] WARN CaveLogger - Failed to initalized map tool
> com.raytheon.uf.viz.core.exception.VizException: Failed to initialize a Tool Resource
> at com.raytheon.uf.viz.core.rsc.tools.GenericToolsResourceData.construct(GenericToolsResourceData.java:138)
> at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.getResource(AbstractGenericToolAction.java:107)
> at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:91)
> at com.raytheon.viz.warngen.gui.WarngenAction.getResource(WarngenAction.java:1)
> at com.raytheon.uf.viz.core.rsc.tools.action.AbstractGenericToolAction.execute(AbstractGenericToolAction.java:76)
> at com.raytheon.viz.warngen.gui.WarngenAction.execute(WarngenAction.java:98)
> at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
> at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
> at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
> at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
> at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
> at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
> at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
> at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
> at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
> at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
> at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
> at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
> at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
> at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
> at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
> at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
> at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
> at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
> at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
> at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
> at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
> at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
> at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> at com.raytheon.uf.viz.personalities.cave.component.CAVEApplication.startComponent(CAVEApplication.java:174)
> at com.raytheon.uf.viz.application.VizApplication.start(VizApplication.java:99)
> at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
> at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
> at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
> Caused by: java.lang.reflect.InvocationTargetException: null
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> at java.lang.reflect.Constructor.newInstance(Unknown Source)
> at com.raytheon.uf.viz.core.rsc.tools.GenericToolsResourceData.construct(GenericToolsResourceData.java:119)
> ... 49 common frames omitted
> Caused by: java.lang.IllegalArgumentException: GeospatialDataAccessor must have geospatial data, geoData is null.
> at com.raytheon.viz.warngen.gui.WarngenLayer$GeospatialDataAccessor.(WarngenLayer.java:349)
> at com.raytheon.viz.warngen.gui.WarngenLayer.init(WarngenLayer.java:2091)
> at com.raytheon.viz.warngen.gui.WarngenLayer.setTemplateName(WarngenLayer.java:2057)
> at com.raytheon.viz.warngen.gui.WarngenLayer.(WarngenLayer.java:1520)
> ... 54 common frames omitted

![Screenshot_2](https://user-images.githubusercontent.com/77472041/123847224-5713f180-d8e4-11eb-9edb-780fcfd00f1f.png)

**Comment by sudokoko** [comment]
+1. Having the same issue.

**Comment by tiffanycmeyer13** [comment]
Can you tell us which localization you are connected to? Our documentation here shows how to tell. (http://unidata.github.io/awips2/cave/cave-localization/)

You will need to be localized to the County Warning Area (CWA), not radar location. We have specific documentation here how to run warngen: http://unidata.github.io/awips2/cave/warngen/

**Comment by sudokoko** [comment]
> Can you tell us which localization you are connected to? Our documentation here shows how to tell. (http://unidata.github.io/awips2/cave/cave-localization/)
> 
> You will need to be localized to the County Warning Area (CWA), not radar location. We have specific documentation here how to run warngen: http://unidata.github.io/awips2/cave/warngen/

Currently localized to IND. AWIPS CAVE running on Windows 7 AMD64 giving this error.

**Comment by tiffanycmeyer13** [comment]
Hello, 

Couple issues - if you are also using KIND for radar data along with WarnGen, there have been having some outages (including radar data almost 12 hours old) which can cause storm motions to be a little wonky and not draw the warning. (This is currently the case this morning). You can check the status of level3 radar data here: https://radar3pub.ncep.noaa.gov/ So be sure in CAVE to look and see if your radar data is up to date if you are experiencing issues. 

As a work-around, if you instead use MRMS or a Reflectivity Composite, you will be able to draw a warning in the IND CWA:
![image](https://user-images.githubusercontent.com/65614396/155339636-79ff867d-6ec1-4696-966c-f19b1944f447.png)


Additionally, we suggest upgrading your Windows to a more recent version Operating System. Windows 7 has been at end of life since Jan 14, 2020 (https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information) and we can not guarantee our software to work on it.

**Comment by sudokoko** [comment]
The issue I’ve been having is the WarnGen dialog refusing to even launch. The error the OP provided is the error I am getting.

**Comment by tiffanycmeyer13** [comment]
Can you send us a screencapture of your CAVE display as well as the CAVE > Preferences > Localization GUI?

**Comment by sudokoko** [comment]
Unable to access the workstation I used but will do so once I can.

**Comment by tiffanycmeyer13** [comment]
Thanks. I also recommend removing caveData before switching localizations: http://unidata.github.io/awips2/install/common-problems/#windows
