### ISSUE TITLE
com.raytheon.viz.gfe/localization/gfe/userPython/utilities/MasterInterface.py ImportError: No module named VTECTable

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#38]
```
WARN  2015-11-10 11:49:07,792 [main] CaveLogger: Error importing the following procedures:
MergeHazards
Traceback (most recent call last):
  File "/home/awips/awips2-builds/cave/com.raytheon.viz.gfe/localization/gfe/userPython/utilities/MasterInterface.py", line 64, in importModules
    MasterInterface.addModule(self, split[0])
  File "/home/awips/awips2-builds/cave/com.raytheon.viz.gfe/localization/gfe/userPython/utilities/MasterInterface.py", line 142, in addModule
    __import__(moduleName)
  File "/home/awips/awips2-builds/cave/com.raytheon.viz.gfe/localization/gfe/userPython/procedures/MergeHazards.py", line 50, in <module>
    import HazardUtils
  File "/home/awips/awips2-builds/cave/com.raytheon.viz.gfe/localization/gfe/userPython/utilities/HazardUtils.py", line 32, in <module>
    import VTECTable
ImportError: No module named VTECTable
'''
```

**Comment by mjames-upc** [comment]
likely a problem with include paths for jep
