### ISSUE TITLE
Type issue leading to EDEXingest not running in 18.2.1-3

### ISSUE THREAD

**Issue by NaderCHASER** [Unidata/awips2#412]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
18.2.1-3
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
CentOS 7
* a description of the issue with the steps needed to reproduce it

> ERROR 2022-01-04 18:11:24,094 9266 [EDEXMain] Main: Error occurred during startup: 
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at com.raytheon.uf.edex.esb.Main.main(Main.java:161) ~[com.raytheon.uf.edex.esb.camel.launcher.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60) [wrapperApp.jar:na]
	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43) [wrapperApp.jar:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'loctablesIngest' defined in class path resource [res/spring/loctables-spring.xml]: Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [com.raytheon.uf.edex.ndm.dataplugin.ingest.NationalDatasetIngester] to required type [com.raytheon.uf.edex.ndm.ingest.IDataSetIngester]: Failed to convert value of type 'com.raytheon.uf.edex.ndm.dataplugin.ingest.NationalDatasetIngester' to required type 'com.raytheon.uf.edex.ndm.ingest.IDataSetIngester'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'com.raytheon.uf.edex.ndm.dataplugin.ingest.NationalDatasetIngester' to required type 'com.raytheon.uf.edex.ndm.ingest.IDataSetIngester': no matching editors or conversion strategy found
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1201) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1103) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at com.raytheon.uf.edex.esb.camel.Executor.start(Executor.java:186) ~[com.raytheon.uf.edex.esb.camel.jar:na]
	... 11 common frames omitted

https://github.com/Unidata/awips2/blob/80ba94bedcb3319b426ef81d5878f46f54bd4749/edexOsgi/com.raytheon.uf.edex.plugin.loctables/res/spring/loctables-spring.xml#L7

https://github.com/Unidata/awips2/blob/01c0bcc22d703228ac6a6a8cdaebfad90d9fe2a8/edexOsgi/com.raytheon.uf.edex.ndm.dataplugin/res/spring/ndm-dataplugin-ingest.xml#L8

Type is `com.raytheon.uf.edex.ndm.dataplugin.ingest.NationalDatasetIngester` 

https://github.com/Unidata/awips2/blob/80ba94bedcb3319b426ef81d5878f46f54bd4749/edexOsgi/com.raytheon.uf.edex.plugin.loctables/src/com/raytheon/uf/edex/plugin/loctables/ingest/LocationTablesIngest.java#L94

Expected type is `com.raytheon.uf.edex.ndm.ingest.IDataSetIngester`

**Comment by tiffanycmeyer13** [comment]
Hello, 

We have updated our source code to fix this issue and new RPM's are now available to download. These new RPM's are considered to be build 18.2.1-4.

More information can be found here:
https://www.unidata.ucar.edu/blogs/news/entry/minor-release-awips-edex-18
