### ISSUE TITLE
Invalid data format encountered during decompression

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#44]
```
ERROR 2016-01-02 23:29:58,494 [Ingest.dpa-1] RadarDecompressor: EDEX - Invalid data format encountered during decompression on /awips2/data_store/radar/HKM/N0S/SDUS50_HKM_N0S_022311_208041570.rad
java.util.zip.DataFormatException: invalid stored block lengths
        at java.util.zip.Inflater.inflateBytes(Native Method) ~[na:1.7.0_65]
        at java.util.zip.Inflater.inflate(Inflater.java:259) ~[na:1.7.0_65]
        at com.raytheon.edex.plugin.radar.RadarDecompressor.decompressRadar(RadarDecompressor.java:241) [com.raytheon.edex.plugin.radar.jar:na]
        at com.raytheon.edex.plugin.radar.RadarDecompressor.decompressImpl(RadarDecompressor.java:104) [com.raytheon.edex.plugin.radar.jar:na]
        at com.raytheon.edex.plugin.radar.RadarDecompressor.decompressWithHeader(RadarDecompressor.java:78) [com.raytheon.edex.plugin.radar.jar:na]
        at sun.reflect.GeneratedMethodAccessor316.invoke(Unknown Source) ~[na:na]

...
```

**Comment by mjames-upc** [comment]
DHR as well

```
ERROR 2016-01-02 23:34:00,695 [Ingest.dhr-1] RadarDecompressor: EDEX - Invalid data format encountered during decompression on /awips2/data_store/radar/HKM/N0S/SDUS50_HKM_N0S_022311_208041570.rad
```

**Comment by mjames-upc** [comment]
Firstly, N0S/SDUS50_HKM_N0S_022311_208041570.rad should never have been processed by Ingest.dpa.
