### ISSUE TITLE
Ingest.Radar: Error occurred during persist SQLGrammarException: could not execute batch

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#45]
```
ERROR 2016-01-03 19:45:05,683 [Ingest.Radar-1] IndexSrv: Error occurred during persist
org.hibernate.exception.SQLGrammarException: could not execute batch
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]

...

Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into radar (forecastTime, refTime, utilityFlags, rangeEnd, rangeStart, insertTime, dataURI, displayModes, elevation, elevationNumber, format, gateResolution, icao, istart, jstart, lastElevationAngle, latitude, layer, location_rda_id, longitude, mnemonic, numBins, numLevels, numRadials, operationalMode, primaryElevationAngle, productCode, trueElevationAngle, unit, volScanTime, volumeCoveragePattern, volumeScanNumber, xscale, yscale, id) values (0, '2016-01-03 18:39:20.000000 +00:00:00', '[]', '2016-01-03 18:39:20.000000 +00:00:00', '2016-01-03 18:39:20.000000 +00:00:00', '2016-01-03 19:45:05.639000 +00:00:00', '/radar/2016-01-03_18:39:20.0/kokx/56/0.0/0.5', 'V', 198.0, 1, 'Radial', 1000, 'kokx', NULL, 0, '0', 40.865, 0.0, 'KOKX', -72.864, 'SRM', 230, 16, 361, 1, 0.5, 56, 0.5, 'kts', '2016-01-03 18:41:55.000000 +00:00:00', 32, 78, NULL, NULL, 11819240) was aborted.  Call getNextException to see the cause.
    at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743) ~[postgresql-9.3-1102.jdbc4.jar:na]
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928) ~[postgresql-9.3-1102.jdbc4.jar:na]
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405) ~[postgresql-9.3-1102.jdbc4.jar:na]
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892) ~[postgresql-9.3-1102.jdbc4.jar:na]
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1135) ~[c3p0-0.9.2.1.jar:0.9.2.1]
    at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:113) ~[hibernate-core-4.2.15.Final.jar:4.2.15.Final]
    ... 79 common frames omitted
INFO  2016-01-03 19:45:05,684 [Ingest.Radar-1] Ingest: EDEX: Ingest - radar-sbn:: /awips2/data_store/radar/OKX/N0S/SDUS51_OKX_N0S_031839_210306688.rad processed in: 0.0470 (sec) Latency: 260.6730 (sec)
```

**Comment by mjames-upc** [comment]
```
metadata=# insert into radar (forecastTime, refTime, utilityFlags, rangeEnd, rangeStart, insertTime, dataURI, displayModes, elevation, elevationNumber, format, gateResolution, icao, istart, jstart, lastElevationAngle, latitude, layer, location_rda_id, longitude, mnemonic, numBins, numLevels, numRadials, operationalMode, primaryElevationAngle, productCode, trueElevationAngle, unit, volScanTime, volumeCoveragePattern, volumeScanNumber, xscale, yscale, id) values (0, '2016-01-03 18:39:20.000000 +00:00:00', '[]', '2016-01-03 18:39:20.000000 +00:00:00', '2016-01-03 18:39:20.000000 +00:00:00', '2016-01-03 19:45:05.639000 +00:00:00', '/radar/2016-01-03_18:39:20.0/kokx/56/0.0/0.5', 'V', 198.0, 1, 'Radial', 1000, 'kokx', NULL, 0, '0', 40.865, 0.0, 'KOKX', -72.864, 'SRM', 230, 16, 361, 1, 0.5, 56, 0.5, 'kts', '2016-01-03 18:41:55.000000 +00:00:00', 32, 78, NULL, NULL, 11819240);
ERROR:  column "volumescannumber" of relation "radar" does not exist
LINE 1: ...nAngle, unit, volScanTime, volumeCoveragePattern, volumeScan...
                                                             ^
```
