### ISSUE TITLE
Windows - Some models report "Unexpected array size" for GridResources/GridData

### ISSUE THREAD

**Issue by Aeasala** [Unidata/awips2#505]
I am using CAVE 18.2.1-3 on Windows 11.
My installation has followed the instruction guide to a T as much as possible, running:
> Miniconda 3 @ Python 3.7.6
> JDK (1.8_181)
> Python Module Numpy (1.15.1)
> Python Module Jep (3.8.2)

All environment variables have been set correctly, and gridslice is present.  I am able to perform tasks which involve it such as isentropic analyses just fine.

I'm not able to load some models such as Vertical Circulation (on RAP13, or any other sources for that matter), and my console complains about array lengths.  If I can recall, my CentOS 7 setup seemed to load it without issue.

Some other models will report the same issue, appearing to successfully be retrieving the raw data (seen through both Wireshark traffic and console output), but unable to process it?

```
16:28:02.313 [main] WARN CaveLogger - Error requesting data for RAP13 1000MB Vertical Circulation  ()   04.20   0HR Sat 20:00Z 04-Mar-23: Unexpected IDataRecord array length: 3
com.raytheon.uf.viz.core.exception.VizException: Unexpected IDataRecord array length: 3
        at com.raytheon.viz.grid.rsc.general.GridResource.getData(GridResource.java:122)
        at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:243)
        at com.raytheon.viz.grid.rsc.general.GridResource.getData(GridResource.java:84)
        at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestRunner.processOneRequest(GridDataRequestRunner.java:117)
        at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestJobPool$GridDataRequestJob.run(GridDataRequestJobPool.java:120)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by tiffanycmeyer13** [comment]
Hello,

Thank you for bringing up this issue. I can confirm I'm seeing the same error on both our CentOS 7 and Windows installs. We will add this to our list of bugs.
