### ISSUE TITLE
PSQLException: ERROR: column "region" does not exist

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#54]
```
ERROR 2016-01-23 21:26:12,912 [EDEXMain] CoreDao: EDEX - Error executing script.
org.postgresql.util.PSQLException: ERROR: column "region" does not exist
  Position: 13
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:397) ~[postgresql-9.3-1102.jdbc4.jar:na]
        at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:909) ~[c3p0-0.9.2.1.jar:0.9.2.1]
        at com.raytheon.uf.edex.database.dao.CoreDao.executeNativeSql(CoreDao.java:868) [com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.dao.CoreDao.executeNativeSql(CoreDao.java:918) [com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.uf.edex.database.tasks.SqlQueryTask.execute(SqlQueryTask.java:76) [com.raytheon.uf.edex.database.jar:na]
        at com.raytheon.edex.plugin.gfe.textproducts.Configurator.execute(Configurator.java:212) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.reference.MapManager.<init>(MapManager.java:243) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.reference.MapManager.<init>(MapManager.java:164) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.server.IFPServer.<init>(IFPServer.java:206) [com.raytheon.edex.plugin.gfe.jar:na]
JEP WARNING: Unsafe reuse of thread EDEXMain for another Python interpreter.
        at com.raytheon.edex.plugin.gfe.server.IFPServer.activateServer(IFPServer.java:134) [com.raytheon.edex.plugin.gfe.jar:na]
 Potential issues can occur if you reuse the thread that JEP was initialized on or have multiple Jep instances on the same thread.
        at com.raytheon.edex.plugin.gfe.config.GFESiteActivation.internalActivateSite(GFESiteActivation.java:302) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.edex.plugin.gfe.config.GFESiteActivation.activateSite(GFESiteActivation.java:240) [com.raytheon.edex.plugin.gfe.jar:na]
        at com.raytheon.uf.edex.site.SiteAwareRegistry.register(SiteAwareRegistry.java:116) [com.raytheon.uf.edex.site.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_65]

```

**Comment by mjames-upc** [comment]
```
su - awips
psql maps
maps=# \dt *.*
                      List of relations
       Schema       |          Name           | Type  | Owner 
--------------------+-------------------------+-------+-------
 mapdata            | airport                 | table | awips
 mapdata            | allrivers               | table | awips
 mapdata            | artcc                   | table | awips
 mapdata            | basins                  | table | awips
 mapdata            | canada                  | table | awips
 mapdata            | city                    | table | awips
 mapdata            | county                  | table | awips
 mapdata            | customlocations         | table | awips
 mapdata            | cwa                     | table | awips
 mapdata            | ffmp_basins             | table | awips
 mapdata            | ffmp_streams            | table | awips
 mapdata            | firewxaor               | table | awips
 mapdata            | firewxzones             | table | awips
 mapdata            | fix                     | table | awips
 mapdata            | highaltitude            | table | awips
 mapdata            | highsea                 | table | awips
 mapdata            | highway                 | table | awips
 mapdata            | hsa                     | table | awips
 mapdata            | interstate              | table | awips
 mapdata            | isc                     | table | awips
 mapdata            | lake                    | table | awips
 mapdata            | latlon10                | table | awips
 mapdata            | lowaltitude             | table | awips
 mapdata            | majorrivers             | table | awips
 mapdata            | map_version             | table | awips
 mapdata            | marinesites             | table | awips
 mapdata            | marinezones             | table | awips
 mapdata            | mexico                  | table | awips
 mapdata            | navaid                  | table | awips
 mapdata            | offshore                | table | awips
 mapdata            | railroad                | table | awips
 mapdata            | rfc                     | table | awips
 mapdata            | specialuse              | table | awips
 mapdata            | states                  | table | awips
 mapdata            | timezones               | table | awips
 mapdata            | warngenloc              | table | awips
 mapdata            | world                   | table | awips
 mapdata            | zone                    | table | awips

maps=# \d mapdata.cwa
                                        Table "mapdata.cwa"
     Column     |         Type         |                         Modifiers                         
----------------+----------------------+-----------------------------------------------------------
 gid            | integer              | not null default nextval('mapdata.cwa_gid_seq'::regclass)
 cwa            | character varying(9) | 
 wfo            | character varying(3) | 
 lon            | double precision     | 
 lat            | double precision     | 
 the_geom       | geometry             | 
 the_geom_0     | geometry             | 
 the_geom_0_064 | geometry             | 
 the_geom_0_016 | geometry             | 
 the_geom_0_004 | geometry             | 
 the_geom_0_001 | geometry             | 
Indexes:
    "cwa_pkey" PRIMARY KEY, btree (gid)
    "cwa_the_geom_0_001_gist" gist (the_geom_0_001)
    "cwa_the_geom_0_004_gist" gist (the_geom_0_004)
    "cwa_the_geom_0_016_gist" gist (the_geom_0_016)
    "cwa_the_geom_0_064_gist" gist (the_geom_0_064)
    "cwa_the_geom_0_gist" gist (the_geom_0)
    "cwa_the_geom_gist" gist (the_geom)
Check constraints:
    "enforce_dims_the_geom" CHECK (st_ndims(the_geom) = 2)
    "enforce_dims_the_geom_0" CHECK (st_ndims(the_geom_0) = 2)
    "enforce_dims_the_geom_0_001" CHECK (st_ndims(the_geom_0_001) = 2)
    "enforce_dims_the_geom_0_004" CHECK (st_ndims(the_geom_0_004) = 2)
    "enforce_dims_the_geom_0_016" CHECK (st_ndims(the_geom_0_016) = 2)
    "enforce_dims_the_geom_0_064" CHECK (st_ndims(the_geom_0_064) = 2)
    "enforce_geotype_the_geom" CHECK (geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL)
    "enforce_geotype_the_geom_0" CHECK (geometrytype(the_geom_0) = 'MULTIPOLYGON'::text OR the_geom_0 IS NULL)
    "enforce_geotype_the_geom_0_001" CHECK (geometrytype(the_geom_0_001) = 'MULTIPOLYGON'::text OR the_geom_0_001 IS NULL)
    "enforce_geotype_the_geom_0_004" CHECK (geometrytype(the_geom_0_004) = 'MULTIPOLYGON'::text OR the_geom_0_004 IS NULL)
    "enforce_geotype_the_geom_0_016" CHECK (geometrytype(the_geom_0_016) = 'MULTIPOLYGON'::text OR the_geom_0_016 IS NULL)
    "enforce_geotype_the_geom_0_064" CHECK (geometrytype(the_geom_0_064) = 'MULTIPOLYGON'::text OR the_geom_0_064 IS NULL)
    "enforce_srid_the_geom" CHECK (st_srid(the_geom) = 4326)
    "enforce_srid_the_geom_0" CHECK (st_srid(the_geom_0) = 4326)
    "enforce_srid_the_geom_0_001" CHECK (st_srid(the_geom_0_001) = 4326)
    "enforce_srid_the_geom_0_004" CHECK (st_srid(the_geom_0_004) = 4326)
    "enforce_srid_the_geom_0_016" CHECK (st_srid(the_geom_0_016) = 4326)
    "enforce_srid_the_geom_0_064" CHECK (st_srid(the_geom_0_064) = 4326)


```
