### ISSUE TITLE
Ingest.Warning: No MND date line to start overview text 

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#61]
```
ERROR 2016-03-20 03:06:49,207 [Ingest.Warning-1] warning: Exchange[ExchangePattern: InOnly, BodyType: java.io.File, Body: [Body is file based: /awips2/data_store/svrwx/20160320/03/NWUS22_KWNS_200306_440312350.2016032003], CaughtExceptionType: com.raytheon.edex.exception.DecoderException, CaughtExceptionMessage: jep.JepException: <type 'exceptions.Exception'>: No MND date line to start overview text >>>   File "<string>", line 1, in <module>
  File "/awips2/edex/data/utility/common_static/base/python/DecoderInterface.py", line 50, in decode
    result = dec.decode()
  File "/awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py", line 1102, in decode
    return decoder.decode()
  File "/awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py", line 198, in decode
    self._overviewText, linePos = self._getOverviewText(linePos)
  File "/awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py", line 379, in _getOverviewText
    raise Exception, "No MND date line to start overview text"
, StackTrace: com.raytheon.edex.exception.DecoderException: jep.JepException: <type 'exceptions.Exception'>: No MND date line to start overview text >>>   File "<string>", line 1, in <module>
  File "/awips2/edex/data/utility/common_static/base/python/DecoderInterface.py", line 50, in decode
    result = dec.decode()
  File "/awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py", line 1102, in decode
    return decoder.decode()
  File "/awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py", line 198, in decode
    self._overviewText, linePos = self._getOverviewText(linePos)
  File "/awips2/edex/lib/plugins/com.raytheon.edex.plugin.warning.jar/WarningDecoder.py", line 379, in _getOverviewText
    raise Exception, "No MND date line to start overview text"

        at com.raytheon.uf.edex.python.decoder.PythonDecoder.decode(PythonDecoder.java:107)
        at com.raytheon.uf.edex.python.decoder.PythonDecoder.decode(PythonDecoder.java:85)
        at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
        at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
        at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
```

**Comment by mjames-upc** [comment]
same issue as #52 and #41
