### ISSUE TITLE
ERROR com.raytheon.uf.common.dataplugin.PluginException: Error occurred purging orphans. 

### ISSUE THREAD

**Issue by mjames-upc** [Unidata/awips2#86]
```
ERROR 2016-06-27 19:00:03,504 [Camel (clusteredpurgeContext) thread #20 - timer://purgeOrphan] purge: Exchange[ExchangePattern: InOnly, BodyType: null, CaughtExceptionType: com.raytheon.uf.common.dataplugin.PluginException, CaughtExceptionMessage: Error occurred purging orphans. , StackTrace: com.raytheon.uf.common.dataplugin.PluginException: Error occurred purging orphans. 
Error occurred purging orphans. 
    at com.raytheon.uf.edex.database.plugin.PluginDao.purgeOrphanedData(PluginDao.java:1253)
    at com.raytheon.uf.edex.purgesrv.PurgeManager.purgeOrphanedData(PurgeManager.java:475)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
    at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
    at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
    at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
    at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
    at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
    at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
    at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:115)
    at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:86)
    at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
    at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:70)
    at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
    at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
    at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:165)
    at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:73)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: com.raytheon.uf.common.datastorage.StorageException: Error deserializing request: Traceback (most recent call last):
   File "/awips2/python/lib/python2.7/site-packages/pypies/handlers.py", line 76, in pypies_response
    obj = dynamicserialize.deserialize(data)
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/__init__.py", line 58, in deserialize
    return dsm.deserializeBytes(bytes)
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/DynamicSerializationManager.py", line 52, in deserializeBytes
    obj = self._deserialize(ctx)
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/DynamicSerializationManager.py", line 47, in _deserialize
    return ctx.deserializeMessage()
   File "/awips2/python/lib/python2.7/site-packages/dynamicserialize/ThriftSerializationContext.py", line 169, in deserializeMessage
    clz = dsObjTypes[name]
 KeyError: 'com.raytheon.uf.common.pypies.request.DeleteOrphansRequest'

    at com.raytheon.uf.common.pypies.PyPiesDataStore.sendRequest(PyPiesDataStore.java:303)
    at com.raytheon.uf.common.pypies.PyPiesDataStore.sendRequest(PyPiesDataStore.java:277)
    at com.raytheon.uf.common.pypies.PyPiesDataStore.deleteOrphanData(PyPiesDataStore.java:461)
    at com.raytheon.uf.edex.database.plugin.PluginDao.purgeOrphanedData(PluginDao.java:1251)
    ... 26 more
]
```

**Comment by mjames-upc** [comment]
similar but different, relating to hdf5 orphans being purged, this seems to run at startup though. 

```
ERROR 2017-03-31 21:17:24,843 1103 [Camel (clusteredpurgeContext) thread #5 - timer://purgeOrphan] purge: Exchange[ExchangePattern: InOnly, BodyType: null, CaughtExceptionType: java.lang.NullPointerException, CaughtExceptionMessage: null, StackTrace: java.lang.NullPointerException
	at com.raytheon.uf.edex.database.plugin.PluginDao.getPurgeRulesForPlugin(PluginDao.java:1904)
	at com.raytheon.uf.edex.database.plugin.PluginDao.purgeOrphanedData(PluginDao.java:1236)
	at com.raytheon.uf.edex.purgesrv.PurgeManager.purgeOrphanedData(PurgeManager.java:475)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:115)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:86)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:70)
	at com.raytheon.uf.edex.esb.camel.MessageProducer$2.process(MessageProducer.java:432)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:91)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:165)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:73)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
]
```
