### ISSUE TITLE
No module named `gridslice` when loading isentropic datasets

### ISSUE THREAD

**Issue by jaredwsmith** [Unidata/awips2#96]
On macOS Sierra and OS X El Capitan:

After getting jep built and into /Library/Java/Extensions, I can now plot wind data. This revealed a new exception: `No module named gridslice` is now getting thrown whenever I try to request the isentropic products.

Here is the stack trace:

```
com.raytheon.uf.viz.core.exception.VizException: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:209)
	at com.raytheon.viz.grid.rsc.general.GridResource.getData(GridResource.java:84)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestRunner.processOneRequest(GridDataRequestRunner.java:117)
	at com.raytheon.uf.viz.core.grid.rsc.data.GridDataRequestJobPool$GridDataRequestJob.run(GridDataRequestJobPool.java:120)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
	at com.raytheon.viz.grid.record.RequestableDataRecord.getDataRecord(RequestableDataRecord.java:123)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecords(GridDataCubeAdapter.java:368)
	at com.raytheon.uf.viz.datacube.AbstractDataCubeAdapter.getRecord(AbstractDataCubeAdapter.java:265)
	at com.raytheon.viz.grid.util.GridDataCubeAdapter.getRecord(GridDataCubeAdapter.java:127)
	at com.raytheon.uf.viz.datacube.AbstractDataCubeAdapter.getRecord(AbstractDataCubeAdapter.java:251)
	at com.raytheon.uf.viz.datacube.DataCubeContainer.getDataRecord(DataCubeContainer.java:111)
	at com.raytheon.viz.grid.rsc.general.D2DGridResource.getData(D2DGridResource.java:194)
	... 4 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: jep.JepException: <type 'exceptions.ImportError'>: No module named gridslice
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
	at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
	at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:199)
	at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
	... 11 common frames omitted
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: jep.JepException: <type 'exceptions.ImportError'>: No module named gridslice
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: No module named gridslice
	at jep.Jep.eval(Jep.java:471)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.executeFunctionInternal(MasterDerivScript.java:127)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScript.executeFunction(MasterDerivScript.java:92)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptExecutor.execute(MasterDerivScriptExecutor.java:62)
	at com.raytheon.uf.common.derivparam.python.MasterDerivScriptExecutor.execute(MasterDerivScriptExecutor.java:1)
	at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:233)
	... 6 common frames omitted
Caused by: jep.JepException: <type 'exceptions.ImportError'>: No module named gridslice
	at /Users/jaredwsmith/Library/CAVE/common/base/derivedParameters/functions/Slice.<module>(Slice.py:21)
	at /Users/jaredwsmith/Library/CAVE/common/base/derivedParameters/python/DerivParamImporter.__addToModule(DerivParamImporter.py:77)
	at /Users/jaredwsmith/Library/CAVE/common/base/derivedParameters/python/DerivParamImporter.load_module(DerivParamImporter.py:69)
```

I looked in a few obvious (to me) places and sure enough wasn't able to find `gridslice`. Seems as if this is a proprietary component so I'm filing it here; let me know if I should be doing support tickets for these too!

**Comment by mjames-upc** [comment]
Submitting issues on github works, thanks for your feedback on this, I'm still working on pydev issues to resolve derived parameters, and will look at this for the next OS X release.

**Comment by jaredwsmith** [comment]
Quick heads up that this is still occurring in 17.1.1 on macOS.

**Comment by mjames-upc** [comment]
As a workaround download https://github.com/Unidata/awips2/blob/unidata_17.1.1-orphan/nativeLib/gridslice/src/gridslice.so to `/Library/Python/2.7/site-packages/` then restart CAVE and reload the isentropic bundles.   

I'll add the library to the dependency package along w jep and get a new release out shortly,

**Comment by jaredwsmith** [comment]
Working perfectly 👍  Thanks Michael!
